import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const file = new URL('../../tool/src/js/39_programs.js', import.meta.url);
assert.ok(fs.existsSync(file), '显卡程序应支持按需初始化');
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync(file, 'utf8'), ctx);
const glSource = fs.readFileSync(new URL('../../tool/src/js/40_gl.js', import.meta.url), 'utf8');
assert.match(glSource, /function compile\(vs, fs\)\s*\{\s*return lazyProgram\(\(\) => compileNow\(vs, fs\)\);/, '所有既有程序仍走统一的按需编译入口');
let count = 0;
const p = {}, u = {};
const lazy = ctx.lazyProgram(() => { count++; return {p, u}; });
assert.equal(count, 0, '未使用的程序不能在启动时编译');
assert.equal(lazy.u, u, '先访问uniform也能初始化');
assert.equal(lazy.p, p);
assert.equal(lazy.u, u);
assert.equal(count, 1, '两个属性共用同一次编译');
assert.equal(Object.getOwnPropertyDescriptor(lazy, 'p').get, undefined, '热路径应直接取值');
let attempts = 0;
const retry = ctx.lazyProgram(() => { if (++attempts === 1) throw Error('compile failed'); return {p, u}; });
assert.throws(() => retry.p, /compile failed/);
assert.equal(retry.p, p);
assert.equal(attempts, 2, '失败不可发布半成品');
console.log('PASS: 延迟编译、p/u共用、热路径直接取值、失败重试');
