// SCHEMA 外真实字段。保留重复入口的数据别名，不增加参数。
const rows=[];
const add=(id,dataPath,scope,label,unit,kind,meaning,oldPosition,source,condition='所在工作区/对象适用时',domIds=[],extra={})=>rows.push({fieldId:id,key:dataPath.split('.').at(-1),dataPath,scope,object:scope==='L'?'当前组合层':scope==='M'?'当前层材质/颜色':scope==='P'?'当前层制作/输出':'浏览器查看/本机交付设置',label,unit,kind,meaning,oldPosition,A:oldPosition,B:oldPosition,source,fieldCondition:condition,domIds,...extra});
for(const [k,label,unit,kind,ids] of [
 ['form','产物形式','选项','select',['x-form']],['texW','贴图宽','px','select',['x-texW']],['texH','贴图高','px','select',['x-texH']],['cols','列数','列','select',['x-cols']],['rows','行数','行','select',['x-rows']],['chans','通道','选项','select',['x-chans']],['outMode','输出拆分','选项','select',['x-out']],['encGamma','编码','选项','select',['x-enc']],['frameMode','取帧方式','选项','select',['x-frame']],['zoom','取景方式','选项','select',['x-zoom']],['unitFlip','星头朝下','开关','checkbox',['x-flip']],['autoGrid','自动格子','开关','checkbox',['x-autogrid']]
])add('SPEC-'+k,'P.'+k,'P',label,unit,kind,({form:'产物形式由花型决定：空中母版/分段，地面循环，升空尾缀V5及打开的旧形式；切形式可同步规格',unitFlip:'单束或升空星头循环贴图朝下；不改变整层弹道',autoGrid:'非母版/分段形式自动安排格子；母版/分段入口隐藏'})[k]||'原贴图规格字段；70_ui.js syncExport呈现，90_events.js直接绑定对应P键','参数 / 当前层 / 输出 / '+(['texW','texH','cols','rows'].includes(k)?'直接调':'贴图')+' / '+label,'tool/src/js/70_ui.js:402; tool/src/js/90_events.js:12','单层或选中组合层的对应输出方案适用',ids);
for(const [k,label,unit,kind,meaning] of [
 ['xw','变色过渡','s','number','颜色段之间过渡宽度'],['headInt','显示强度','×','number','写Color Over Life，不改灰度贴图；拆分输出时作用星头'],['tailInt','尾迹显示强度','×','number','拆分输出尾迹强度'],
 ...[0,1,2,3].map(i=>['ramp'+i,['渐变图暗端','渐变图中暗','渐变图中亮','渐变图亮端'][i],'RGB色值','color','灰度亮度查Ramp，颜色选择器编辑']),
 ['stages[i][0]','颜色段起始','s','number','当前层绝对时间，从开花0s算；首段固定0，最多5段'],['stages[i][1]','颜色段色值','RGB色值','color','每段颜色，原拾色器/预设修改']
])add('MAT-'+k,'M.'+k,'M',label,unit,kind,meaning,'参数 / 本层颜色 / '+label,'tool/src/js/70_ui.js:559; tool/src/js/70_ui.js:701','本层共用颜色；多层state.M绑定L');
for(const [k,label,unit,kind,condition] of [
 ['delay','开始时间','s','number','组合层；图层行、层设置、时间轴共用；层设置0–10，整体旧入口0–3'],['scale','缩放','×','number','组合层；只改整层合成/导出尺度，不改P初速'],['rate','时间倍率','×','number','组合层播放/输出时间倍率；区别P.tempo改写制作参数'],['mirror','水平镜像','开关','checkbox','组合层'],
 ['out.pc','PC产物','选项','select','PC：seq/unit/dots/frame/off'],['out.mobile','手机产物','选项','select','手机：seq/unit/frame/off，无GPU'],['dotSize','光点大小','×星头','number','PC为dots'],['dotBright','光点亮度','×','number','PC为dots'],['unitVariants','单束变体数','张','number','任一平台unit'],['unitRandom','单束随机感','1','number','任一平台unit'],['lowPick','单帧取法','选项','select','任一平台frame'],['lowAt','单帧时刻','s','number','frame，0自动选最大帧'],['lowSize','单帧边长','px','select','frame'],['lowJit','单帧随机缩放','1','number','frame'],['lowMaps','单帧功能图','选项','select','frame'],['lowSuffix','单帧后缀','文本','text','frame']
])add('LAYER-'+k,'L.'+k,'L',label,unit,kind,'组合层独立字段；与单层P方案同义，保存位置不同','参数 / 当前层 / '+(['delay','scale','rate','mirror'].includes(k)?'效果 / 这一层在整朵里':'输出 / 导出方案')+' / '+label,'tool/src/js/79_workbench.js:buildLayerHead',condition);
const viewDefs=[
 ['dist','state.dist','观察距离','m','range','引擎/实时游戏内大小，滑杆0–1000经对数换算，实际50–1200m'],['expo','state.expo','显示曝光','×','range','仅预览0.2–3，不改P.exposure或贴图'],['autoBakeChk','bakeMode.auto','自动烘焙','开关','checkbox','store autoBake；关闭后按B/查看产物/导出触发烘焙'],['exportResolution','state.exportResolution','按导出分辨率','开关','checkbox','预览设置'],['previewBloomChk','P.previewBloom','预览泛光','开关','checkbox','只改画布，配方快照保留，导出指纹比较剔除'],['speed','state.speed','播放速度','×','select','1/0.5/0.25/0.1'],['loopChk','state.loopPlay','循环播放','开关','checkbox','store loopPlay；关后播放一遍'],['scrub','state.t','播放时刻','s（滑杆0–1000换算）','range','与当前制作范围关联，非曲线关键帧'],['lowDissolve','state.lowDissolve','溶解预览','开关','checkbox','单帧观察'],['lowSide','state.lowSide','单帧并排','开关','checkbox','只改变观察'],['assetDir','DOM.assetDir.files','选择素材包文件夹','文件集合','file','素材只读打开，不改变制作配方'],['assetCut','asset.cutout','素材轮廓','开关','checkbox','素材只读查看'],['assetSky','asset.sky','素材天空','开关','checkbox','素材只读查看']
];
for(const [dom,key,label,unit,kind,condition] of viewDefs)add('VIEW-'+dom,key,'VIEW',label,unit,kind,condition,'画布 / 预览设置 / '+label,dom.startsWith('asset')?'tool/src/js/77_assets.js:311':'tool/src/js/90_events.js',condition,[dom]);
for(const [key,label,condition] of [['q','参数搜索','搜索当前层全部发射器，清除恢复开合'],['changed','仅改动','相对打开/版本基线；store pChanged'],['en','英文名','store pEN；改变名字呈现'],['mopen','模块开合','store pModOpen，按发射器›模块键；当前不是逐层独立'],['ropen','随机开合','store pRandOpen，按本体key'],['tab','发射器选择','store pEmitTab，按家族；切层会共用，不承诺逐对象恢复'],['locks','参数锁','state.locks；阻止号数/随机微调，不锁直接编辑，不属wbSnap'],['linkOff','暂时不联动','state.linkOff；现有候选同批星轨迹组，仅临时状态'],['timeLink','时长/入点跟着走','时间工具；影响时间参数联动，不是所有字段链条']])add('UI-'+key,key==='locks'?'state.locks':key==='linkOff'?'state.linkOff':key==='timeLink'?'state.timeLink':'pview.'+key,'VIEW',label,'状态','view','呈现/操作设置，区别制作参数。'+condition,'参数 / 定位与状态 / '+label,'tool/src/js/70_ui.js; tool/src/js/90_events.js',condition);
add('LINK-groups','lib.my.links / linksLive','L','轨迹联动组','层ID集合','selection','我的效果显式同批星组，P轨迹字段同步，颜色各层独立；wbSnap不含links，必须单独核对保存与撤销边界','参数 / 当前层 / 效果 / 轨迹联动','tool/src/js/79_myfx.js:myLinkHTML','我的效果可编辑；候选按推断组',[],{saveUndoOverride:'links由mySave显式存/另有linksLive；wbSnap仅P/M/L，不含分组本身。不能承诺Ctrl+Z撤销建组；关联引发P数值改变可被快照撤销。'});
add('VIEW-solo','state.layerView.solo','VIEW','独看','层索引','toggle','当前层只看此层，切编辑对象不会自动独看，不改变导出方案','图层管理 / 独看','tool/src/js/79_workbench.js:buildLayerCard');
add('VIEW-mute','state.layerView.mute','VIEW','静音','层索引集合','toggle','观察屏蔽，不等于输出off，不属于wbSnap层内容','图层管理 / 静音','tool/src/js/79_workbench.js:buildLayerCard');
rows.find(x=>x.fieldId==='UI-timeLink').dataPath='state.followOff（反向）';
rows.find(x=>x.fieldId==='UI-timeLink').fieldCondition='store tlFollowOff；关=只改该时间点，开=制作时长/入点跟随；79_workbench.js:658';
add('UI-glue','state.glueOff（反向）','VIEW','同一时刻的点一起动','开关','checkbox','时间点粘连，区别轨迹分组；store tlGlueOff，快照不含此设置','时间轴 / 时间工具 / 同一时刻的点一起动','tool/src/js/79_workbench.js:659','组合且存在轨迹关联组');
add('NAME-base','store.packNames[wbKey()].base','LOCAL','效果英文名','ASCII名称','text','按效果保存，素材包/贴图/UE资产采用同一名；不能随便猜资源映射','交付清单 / 英文名','tool/src/js/79_workbench.js:906', 'ASCII字母/数字/下划线，非空', ['dvBase'],{saveUndo:'浏览器fwb.packNames；我的效果仓库另存；不在wbSnap，参数Ctrl+Z不撤销名称'});
add('NAME-layer','store.packNames[wbKey()].layers[i]','LOCAL','层英文名','ASCII名称','text','整包内部层名称；非空层名不可重复，数据-ly[i]入口','交付清单 / 第i层名称','tool/src/js/79_workbench.js:900','组合层；现有ASCII校验',[],{saveUndo:'同packNames保存，与制作参数撤销分开'});
add('SIZE-pick','store.sizeSpecPick[sizePickKey]','LOCAL','导出尺寸档','标定档ID/none','select','自动按最新尺寸标定；选择只改导出长度不改时间，影响导出指纹；原大/不标定才使用exportScale','交付清单 / 导出尺寸','tool/src/js/66_fwlcascade.js:272; tool/src/js/79_workbench.js:915','存在标定表',['dvSizeSpec'],{saveUndo:'浏览器fwb.sizeSpecPick，参数快照不含选择；应分别提示已保存和素材旧'});
add('DELIVERY-destination','deliveryDestination','LOCAL','导出方式','选项','select','指定目录/下载ZIP独立动作；选择不授权UE写入','资源交付 / 导出方式','tool/src/js/67_delivery.js','目录服务可用',['deliveryDestination'],{saveUndo:'运行时交付设置，不进配方快照/参数撤销'});
add('DELIVERY-root','本机服务config.root','LOCAL','资源导出目录','路径','text','本机目录配置；保存通过真实服务回执，不是Blob路径','资源交付 / 资源导出目录','tool/src/js/67_delivery.js; tool/local_delivery/service.py','仅本机适配器可保存',['deliveryRoot'],{saveUndo:'本机服务持久化，不进配方Ctrl+Z；失败保留填写内容'});
for(const [id,label] of [['type','花型/来源选择'],['fileIn','导入参数JSON'],['pkSearch','模板搜索'],['saveNameInput','保存名称']])add('NAV-'+id,'DOM.'+id,'NAV',label,'文本/选项','navigation','对象/文件操作入口，非粒子物理参数；换效果/版本重置当前撤销栈','对象与文件操作 / '+label,'tool/src/body.html; tool/src/js/70_ui.js','对应操作开启',[id],{saveUndo:'按原对象/文件命令规则，不等同参数数值撤销'});
export default rows;
