import React,{useEffect,useRef} from 'react';
import {ArrowLeft} from '@phosphor-icons/react';
import {recipeGeometry} from './recipe-geometry.mjs';
import {drawRecipeReference} from './recipe-preview-renderer.mjs';

import {staticBaseRecipe} from './basic-template-model.mjs';
const examples=[{id:'small',label:'小号主排',x:-450,z:300,d:90},{id:'medium',label:'中号主排',x:-230,z:360,d:150},{id:'large',label:'大号主排',x:30,z:480,d:230},{id:'wall',label:'白色墙参照',x:380,z:360,d:230},{id:'front',label:'前台小花',x:0,z:125,d:32}];
function StaticShape({resource}){const ref=useRef();useEffect(()=>{const canvas=ref.current,draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;const ctx=canvas.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);ctx.fillStyle='#101a1b';ctx.fillRect(0,0,w,h);const draft=staticBaseRecipe(resource),g=recipeGeometry(draft,w,h);if(resource.role!=='unknown')drawRecipeReference(ctx,g,w,h);if(resource.role==='unknown'){ctx.fillStyle='#bac6c5';ctx.font='13px sans-serif';ctx.textAlign='center';ctx.fillText('资源类型待确认，不生成推测造型',w/2,h/2)}else{const row=g.rows[0];ctx.strokeStyle='#86e0c5';ctx.lineWidth=2;ctx.beginPath();if(resource.role==='burst')ctx.arc(row.end[0],row.end[1],row.radius,0,Math.PI*2);else{ctx.moveTo(...row.start);ctx.lineTo(...row.end)}ctx.stroke()};};draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect()},[resource]);return <canvas ref={ref} className="basic-static-canvas" aria-label="基础模板静态单束或原地球花预览"/>;}
function ScaleOverview({resource,doc}){const ref=useRef();useEffect(()=>{const canvas=ref.current,draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;const ctx=canvas.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);ctx.fillStyle='#101a1b';ctx.fillRect(0,0,w,h);const unit=Math.min((w-55)/1200,(h-35)/675),ox=w/2,ground=h-20,xy=(x,z)=>[ox+x*unit,ground-z*unit];ctx.strokeStyle='#667a80';ctx.fillStyle='#a5b7ba';ctx.lineWidth=1.5;const rect=(x,z,width,height)=>{const [px,py]=xy(x,z);ctx.strokeRect(px,py,width*unit,height*unit)};rect(-400,150,800,150);for(const x of [-400,-250,-100,100,250,400]){const [a,b]=xy(x,150);ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(a,ground);ctx.stroke()}rect(-100,50,200,50);ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText('大坝 800m · 坝顶 150m · 前台 50m',ox,ground-4);
 for(const e of examples){const [x,y]=xy(e.x,e.z),r=e.d/2*unit,chosen=resource.sizeClass===e.id||resource.role==='burst'&&resource.sizeClass==='large'&&e.id==='wall'&&/墙/.test(resource.label||'');ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle=chosen?'#86e0c5':'#617271';ctx.fillStyle=chosen?'rgba(134,224,197,.13)':'rgba(110,130,126,.03)';ctx.lineWidth=chosen?2.5:1;ctx.fill();ctx.stroke();ctx.fillStyle=chosen?'#9cebd3':'#bac6c5';ctx.fillText(e.label,x,y-r-23);ctx.font='11px sans-serif';ctx.fillText('离地 '+e.z+'m · Ø'+e.d+'m',x,y-r-7);ctx.font='12px sans-serif'}
 const [sx,sy]=xy(430,35);ctx.strokeStyle='#99b4b4';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx,sy-3);ctx.lineTo(sx,sy+3);ctx.moveTo(sx,sy);ctx.lineTo(sx+100*unit,sy);ctx.moveTo(sx+100*unit,sy-3);ctx.lineTo(sx+100*unit,sy+3);ctx.stroke();ctx.fillStyle='#b6c7c7';ctx.fillText('100 m',sx+50*unit,sy-8)};draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect()},[resource,doc]);return <canvas ref={ref} className="basic-scale-canvas" aria-label={'1200×675米设计规格对照；当前'+(resource.sizeClass==='unknown'?'资源待标定':resource.sizeClass)+'选中'}/>;}
export function BasicTemplatePreview({resource,doc,onBack,onUse}){return <><section className="stage-panel recipe-preview basic-preview"><div className="panel-heading"><b>基础模板 · {resource.label||resource.name}</b><button onClick={onBack}><ArrowLeft size={15}/>返回舞台</button></div><div className="basic-static-title">原始形态 · 静态 <small>{resource.role==='burst'?'原地球花；无升空位移':resource.role==='unknown'?'类型未确认；仅作资源参考':'单束垂直向上示意；无扫射编排'}</small></div><StaticShape resource={resource}/><div className="basic-static-title">设计规格对照 <small>目标比例，实际资源待标定</small></div><ScaleOverview resource={resource} doc={doc}/><p className="recipe-note">选中资源对应的大小类别会亮起。未标定资源不冒充实测尺寸；基础模板没有花型的延迟、位置或编排动画。</p></section><aside className="inspector recipe-inspector"><div className="panel-heading"><b>基础模板 · 只读</b></div><div className="inspector-body"><h3>{resource.label||resource.name}</h3><p className="native-info">{resource.id}</p><p className="field-hint">{resource.source==='programme'?'导入节目内资源，资源表中未收录':'ResourceFXTable · '+resource.platforms?.join(' / ')}</p><p className="field-hint">类型：{({trail:'尾缀',burst:'球花',fan:'扇形单束',unknown:'待确认'})[resource.role]} · 大小类别：{({small:'小',medium:'中',large:'大',front:'前台',unknown:'待标定'})[resource.sizeClass]}</p><p className="subtle-note">基础模板只选择资源。延迟、高度、大小、角度与随机范围在花型层中设置。</p>{resource.sourceRows?.map(row=><details key={row.platform}><summary>{row.platform} · 资源表原值</summary><dl><dt>资源行</dt><dd>{row.rowName}</dd><dt>原粒子</dt><dd className="native-info">{row.particle}</dd><dt>表中缩放</dt><dd>{row.scale}</dd><dt>表中寿命 / 延迟</dt><dd>{row.lifeTime} / {row.delay}</dd></dl></details>)}<p className="panel-warning">只读形态及目标米尺；真实单束/整排、球花大小与飞行轨迹仍需引擎核对。</p></div><div className="recipe-save"><button disabled={resource.role==='unknown'} onClick={onUse}>用于当前花型</button></div></aside></>}
