import React,{useState} from 'react';
import {deliveryBase,readResourceIndex,pinResource} from './delivery-resource.mjs';
import './shared-workspace-foundation.css';
import './delivery-resource.css';

export function DeliveryResourcePanel({doc,tier,catalogue,onPin,onError}){
 const [resources,setResources]=useState([]),[selected,setSelected]=useState(null),[status,setStatus]=useState('从烘焙器读取已交付资源；新修订不会替换节目中的固定版本。'),[loading,setLoading]=useState(false),[engineId,setEngineId]=useState(''),[zone,setZone]=useState('dam'),[role,setRole]=useState('burst');
 async function refresh(){setLoading(true);try{const res=await fetch(deliveryBase+'/api/resources');const data=await res.json();if(!res.ok)throw Error(data.error);const items=readResourceIndex(data);setResources(items);setStatus('已读取 '+items.length+' 个完整修订。只在点击“加入花型库”后改变当前节目。');if(selected&&!items.some(r=>r.deliveryId===selected.deliveryId))setStatus('所选资源已缺失或不可读；节目中的旧引用保持。')}catch(e){setStatus('读取失败：'+e.message+'。请启动本机交付服务。')}finally{setLoading(false)}}
 return <section className="delivery-resources fw-scope" aria-label="烘焙器交付资源"><button className="fw-button" onClick={refresh} disabled={loading} aria-busy={loading}>{loading?'读取中…':'读取烘焙器资源'}</button><p role="status">{status}</p><div className="delivered-resource-list">{[...resources].reverse().map(r=><button className="fw-button" key={r.deliveryId} aria-pressed={selected?.deliveryId===r.deliveryId} onClick={()=>{setSelected(r);setEngineId('')}}>{r.thumbnail?.status==='ready'?<img src={deliveryBase+'/api/deliveries/'+r.deliveryId+'/'+r.thumbnail.file} alt={r.name+' 同修订引擎回放'}/>:<span className="thumb-missing">缺缩略图</span>}<span><b>{r.name}</b><small>{r.revisionId.slice(0,8)} · {r.metadata?.artifactDuration||r.metadata?.duration||'待确认'} s</small><small>{r.packages.map(p=>p.platform.toUpperCase()).join(' / ')} · {r.importReceipt?'有导入记录':'待导入'}</small></span></button>)}</div>{selected&&<div className="delivery-resource-binding"><b>{selected.name} · 固定 {selected.revisionId.slice(0,8)}</b><p>填写已登记的 ResourceFX 行名；这是资源配表 ID，区别于贴图名和粒子路径。舞台仍为比例示意。</p><label>ResourceFX 行名<input list="delivery-fx-ids" value={engineId} onChange={e=>setEngineId(e.target.value)}/></label><datalist id="delivery-fx-ids">{(catalogue?.rows||[]).map(r=><option key={r.id} value={r.id}/>)}</datalist><label>资源类型<select value={role} onChange={e=>setRole(e.target.value)}><option value="burst">开花</option><option value="trail">尾缀</option><option value="fan">扇形</option></select></label><label>使用区域<select value={zone} onChange={e=>setZone(e.target.value)}><option value="dam">坝顶</option><option value="front">小平台</option></select></label><button className="fw-button fw-button--primary" disabled={tier!=='high'||!engineId} onClick={()=>{try{onPin(pinResource(doc,selected,{engineId,zone,role}));setStatus('已加入固定修订；从花型库设置发射。原片段保持，可撤销。')}catch(e){onError(e.message)}}}>加入花型库</button>{tier!=='high'&&<p>切到高配后可加入共用编排。</p>}</div>}</section>;
}
