import {FixedDirectorPanel} from './FixedDirectorPanel.jsx';
import {geometryAudit} from './director-geometry.mjs';
import React,{useState,useMemo,useRef,useEffect} from 'react';
import {sourceMapping,SOURCE_BP} from './director-source-map.mjs';
import {compileDirector} from './director-model.mjs';import {ueText} from './delivery-model.mjs';import {downloadText,tiers} from './workbench-data.mjs';
const MAP_KEY='director-source-mapping-v07';
const DEFAULT_BP="Blueprint'/Game/BluePrints/ShowDirector/Instance/Ma5_NewYearFireworks/BP_Failed_NewYearFireworks_ShowDirector_2.BP_Failed_NewYearFireworks_ShowDirector_2'";
function LegacyDirectorPanel({doc,events,tier,setTier,notify}){
 const [path,setPath]=useState(DEFAULT_BP),[sourcePath,setSourcePath]=useState(SOURCE_BP),[data,setData]=useState(null),[mapping,setMapping]=useState({}),[status,setStatus]=useState('读取导演，核对三表与场景绑定'),[busy,setBusy]=useState(false),[format,setFormat]=useState('manifest'),[expanded,setExpanded]=useState(false);const request=useRef(0);
 useEffect(()=>()=>{request.current++},[]);
 async function identify(){const id=++request.current;setBusy(true);setData(null);setMapping({});setStatus('正在读取导演与指定子模板库…');try{const response=await fetch('/api/director?path='+encodeURIComponent(path)+'&source='+encodeURIComponent(sourcePath));const body=await response.json();if(id!==request.current)return;if(!response.ok)throw Error(body.error||'读取失败');setData(body);let m={};try{m=sourceMapping(doc,body.catalog)}catch{}try{const saved=JSON.parse(localStorage.getItem(MAP_KEY)||'null');if(saved?.target===body.target.path&&saved?.sourceFingerprint===body.sourceLibrary.fingerprint)for(const [id,value] of Object.entries(saved.mapping||{}))if(body.catalog.some(s=>s.key===value.source))m[id]=value;}catch{}setMapping(m);setStatus(`已读取 ${body.points.length} 个现场点、${body.catalog.length} 条指定库子模板；同名条目按来源序号区分`)}catch(e){if(id===request.current)setStatus(e.message)}finally{if(id===request.current)setBusy(false)}}
 useEffect(()=>{if(data)try{localStorage.setItem(MAP_KEY,JSON.stringify({target:data.target.path,sourceFingerprint:data.sourceLibrary.fingerprint,mapping}))}catch{}},[data,mapping]);
 function useTest(){try{setMapping(sourceMapping(doc,data.catalog));setStatus('已按指定子模板库重新映射；保留原条目的内部时序和变换');notify('18种花型已重新映射')}catch(e){setStatus(e.message)}}
 const result=useMemo(()=>compileDirector(doc,events,data,mapping),[doc,events,data,mapping]);
 const auditFor=t=>geometryAudit(t,data?.catalog.find(s=>s.key===mapping[t.id]?.source));
 const playbackStatus=data?.receipt?.nativePreviewSmokeObserved?'已短时实播；整场与尺寸仍待验证。':'尚未验证实播。';
 const used=doc.templateLibrary.filter(t=>events.some(e=>e.templateId===t.id));
 const fields={EffectSubTemplates:'1 · 特效子模板库',EffectTemplates:'2 · 特效模板库',EffectScheduleGroups:'3 · 特效时序编排（按分组）'};
 const text=format==='manifest'?JSON.stringify({...result.manifest,quality:tier},null,2):data&&!result.issues.length?ueText(result.arrays[format]):'';
 async function copy(){try{await navigator.clipboard.writeText(text);notify(format==='manifest'?'已复制交付检查清单':'已复制'+fields[format])}catch{setExpanded(true);notify('请展开内容手动复制')}}
 return <><section className="inspector-section"><h3>导演交付 · 替换旧编排</h3><p className="field-hint">P0–P8 / B0–B7 / F0–F6。只生成当前新编排，旧时序不追加。</p><label className="panel-field">测试档位<select aria-label="导演交付档位" value={tier} onChange={e=>setTier(e.target.value)}>{Object.entries(tiers).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="panel-field stacked">导演 BP 资产路径<input aria-label="导演BP路径" value={path} onChange={e=>{request.current++;setPath(e.target.value);setData(null);setMapping({});setBusy(false)}}/></label><label className="panel-field stacked">子模板来源 BP<input aria-label="子模板来源BP" value={sourcePath} onChange={e=>{request.current++;setSourcePath(e.target.value);setData(null);setMapping({});setBusy(false)}}/></label><button className="full" onClick={identify} disabled={busy||!path.trim()}>{busy?'正在读取…':'读取导演与模板库'}</button><p className="field-hint" role="status">{status}</p></section>
 <section className="inspector-section"><h3>新时序 · {tiers[tier]}</h3>{data?.receipt&&<p className="panel-warning">BP 导入已验证 · 高配 · 已保存<br/>{data.instances.some(i=>!i.matchesNewDefaults)?'现场实例仍有旧配置，应用新三表后再实播。':'现场实例配置一致；'+playbackStatus}</p>}<div className="delivery-summary"><b>{result.summary.eventCount}</b><span>次点位播放<small>{result.summary.subTemplates} 子模板 · {result.summary.templates} 模板 · {result.summary.groups} 组</small></span></div><p className="field-hint">模板去重：{result.summary.originalTemplates} → {result.summary.templates}，保留全部 {result.summary.scheduleSlots} 次调度。只合并完全相同的定义，不减少烟花。</p><p className="field-hint">扇形 {events.filter(e=>doc.templateLibrary.find(t=>t.id===e.templateId)?.kind==='fan').length} 次 · 非扇形 {events.filter(e=>doc.templateLibrary.find(t=>t.id===e.templateId)?.kind!=='fan').length} 次。演出 {doc.meta.duration.toFixed(2)} 秒 · 音乐从 {doc.meta.musicOffset} 秒开始。三档分别交付；不把中低档混入同一时序。</p>{data&&<><p className="field-hint">当前引擎配置：{data.config.EffectTemplates.length} 模板 / {data.config.EffectScheduleGroups.length} 组；总时长 {Number(data.config.TotalDuration).toFixed(2)}s。替换目标是此 BP 的默认配置。</p><button className="full" onClick={()=>downloadText('director-original-readback.json',JSON.stringify(data,null,2))}>下载当前导演快照</button>{data.instances.length>1&&<p className="panel-warning">场景有 {data.instances.length} 个相同 DirectorId 的导演，实播前需确定唯一执行实例。</p>}</>}</section>
 {data&&<section className="inspector-section"><h3>新花型资源映射 · {used.length} 种</h3><p className="panel-warning">资源已匹配，尺寸尚未标定。以下预览高度、花径是设计目标；源库的升空段、爆点偏移和触发时间可能不同，不能把当前交付当作外观一致版。</p><p className="field-hint">只使用指定库的条目；来源序号从 0 开始。金扇形按你确认的第 2 条（索引 1）读取。金/银扇形目前共用该条，网页颜色标签不代表引擎资源颜色已区分。</p><button className="full" onClick={useTest}>按指定库重新映射</button>{used.map(t=><details key={t.id}><summary>{t.name} · {mapping[t.id]?.source?'来源 #'+mapping[t.id].sourceIndex:'待指定'}</summary><label className="panel-field stacked">真实子模板<select aria-label={`导演映射 ${t.id}`} value={mapping[t.id]?.source||''} onChange={e=>setMapping(m=>({...m,[t.id]:{...m[t.id],source:e.target.value,sourceIndex:data.catalog.find(s=>s.key===e.target.value)?.sourceIndex,sourcePath:data.sourceLibrary.path,note:'手动指定',mode:t.kind==='fan'?(m[t.id]?.mode||''):'whole'}}))}><option value="">选择对应的真实效果</option>{data.catalog.map(s=><option key={s.key} value={s.key}>#{s.sourceIndex} · {s.sub.TemplateName} · {s.sub.Entries.length} 条效果</option>)}</select><small className="field-hint">{mapping[t.id]?.note}</small><small className="field-hint">目标：相对升空 {auditFor(t).target.riseM} m · {auditFor(t).target.delayS} s · 花径 {auditFor(t).target.diameterM} m。{auditFor(t).anchors.length?auditFor(t).anchors.map(a=>`来源爆点偏移 ${a.heightM.toFixed(1)} m / 延迟 ${a.delayS.toFixed(2)} s`).join("；"):"此素材是扇形或彗星，需测量运动轨迹。"}{auditFor(t).needsRise?" 缺少升空段，需要重新配对尾缀。":""} 可见花径待实测。</small></label>{t.kind==='fan'&&<label className="panel-field stacked">扇形素材方式<select aria-label={`扇形素材方式 ${t.id}`} value={mapping[t.id]?.mode||''} onChange={e=>setMapping(m=>({...m,[t.id]:{...m[t.id],mode:e.target.value}}))}><option value="">请确认素材方式</option><option value="whole">整排素材 · 保留资源内花束</option><option value="beams">单束组合 · 按本片段展开</option></select><small className="field-hint">整排保持已有束数与内部节奏；单束组合才应用网页束数、张角和束间隔。</small></label>}</details>)}</section>}
 {data&&result.issues.length>0&&<details open><summary>待处理 {result.issues.length} 项 · 引擎属性未生成</summary><ul className="field-hint">{result.issues.map(s=><li key={s}>{s}</li>)}</ul></details>}
 <section className="inspector-section"><h3>三组数据</h3><label className="panel-field stacked">输出内容<select aria-label="导演输出内容" value={format} onChange={e=>setFormat(e.target.value)}><option value="manifest">交付检查清单（非原生导入文件）</option>{Object.entries(fields).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><p className="field-hint">完成映射后，依次复制三项到 DefaultConfig 对应数组，整表替换。导演原生 JSON 导入格式还需与其导出样本对齐，当前清单不能直接用于原生导入。</p><details open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>查看生成内容</summary>{expanded&&<textarea aria-label="导演生成内容" className="code-preview" readOnly value={text}/>}</details><div className="pair-actions"><button disabled={!text} onClick={copy}>复制当前项</button><button disabled={!text} onClick={()=>downloadText(`director-${tier}-${format}.${format==='manifest'?'json':'txt'}`,text)}>下载当前项</button></div></section><p className="field-hint">本面板提供实时读取和三表交付；不会自动写入引擎。来源库原参数已保留；正式音乐、实际开花时刻与外观仍需在引擎校准。</p></>;
}

export function DirectorPanel(props){return props.doc.subTemplateLibrary?<FixedDirectorPanel {...props}/>:<LegacyDirectorPanel {...props}/>;}
