import {EnginePanel} from './EnginePanel.jsx';
import {AsyncButton} from './InteractionFeedback.jsx';
import React,{useMemo,useState} from 'react';
import {compileDirector} from './director-model.mjs';
import {ueText} from './delivery-model.mjs';
import {downloadText,tiers} from './workbench-data.mjs';
const fields={EffectSubTemplates:'1 · 特效子模板库',EffectTemplates:'2 · 特效模板库',EffectScheduleGroups:'3 · 特效时序编排'};
export function FixedDirectorPanel({doc,events,tier,setTier,notify}){
 const [format,setFormat]=useState('EffectSubTemplates'),[expanded,setExpanded]=useState(false);
 const result=useMemo(()=>compileDirector(doc,events),[doc,events]);const text=result.issues.length?'':format==='manifest'?JSON.stringify({...result.manifest,quality:tier},null,2):ueText(result.arrays[format]);
 return <><EnginePanel doc={doc} events={events} tier={tier} notify={notify}/><section className="inspector-section"><h3>固定子模板 → 片段 → 时序</h3><p className="field-hint">全部来自当前草稿的固定版本。改变子模板后先保存，三表随之更新。这里不再进行第二次花型映射。</p><label className="panel-field">交付档位<select aria-label="导演交付档位" value={tier} onChange={e=>setTier(e.target.value)}>{Object.entries(tiers).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><div className="delivery-summary"><b>{result.summary.eventCount}</b><span>次点位播放<small>{result.summary.subTemplates} 子模板 · {result.summary.templates} 复用模板 · {result.summary.scheduleSlots} 时序项</small></span></div><p className="field-hint">P0–P8 / B0–B7 / F0–F6，槽位容量固定 9 / 8 / 7。三档分别交付。</p><p className="panel-warning">数据共源已接通；资源视觉和尺寸仍需 UE 标定。新版本尚未导入引擎。</p></section><section className="inspector-section"><h3>导出三表</h3><label className="panel-field stacked">输出内容<select aria-label="导演输出内容" value={format} onChange={e=>setFormat(e.target.value)}>{Object.entries(fields).map(([id,n])=><option key={id} value={id}>{n}</option>)}<option value="manifest">完整交付清单 JSON</option></select></label><p className="field-hint">上方自动导入可直接写入所选导演。需要手动交接时，可复制或下载三表；完整清单用于检查。</p>{result.issues.length>0&&<p role="alert" className="panel-warning">{result.issues.join('；')}</p>}<div className="pair-actions"><AsyncButton pendingLabel="复制中…" disabled={!text} onClick={async()=>{try{await navigator.clipboard.writeText(text);notify('已复制 '+(fields[format]||'完整清单'))}catch{setExpanded(true);notify('剪贴板不可用，请在内容框手动复制','error')}}}>复制当前表</AsyncButton><button disabled={!text} onClick={()=>{downloadText(`director09-${tier}-${format}.${format==='manifest'?'json':'txt'}`,text);notify('已生成下载文件：'+(fields[format]||'完整清单'))}}>下载当前表</button></div><button className="full" disabled={!!result.issues.length} onClick={()=>{downloadText(`director09-${tier}-three-tables.json`,JSON.stringify({...result.manifest,quality:tier,propertyText:Object.fromEntries(Object.keys(fields).map(k=>[k,ueText(result.arrays[k])]))},null,2));notify('已生成三表与检查清单下载文件')}}>下载三表与检查清单</button><details open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>查看当前表</summary>{expanded&&<textarea className="code-preview" aria-label="导演生成内容" readOnly value={text}/>}</details></section><details><summary>本次引用的固定版本</summary><ul className="field-hint">{result.manifest.fixedVersions.map(v=><li key={v.templateId}>{v.templateId} → {v.key}</li>)}</ul></details></>;
}
