import React,{useState,useEffect,useRef} from 'react';
import {Copy,Plus,Trash,ArrowLeft} from '@phosphor-icons/react';
import {RecipeField as Field} from './SubTemplateWorkspace.jsx';
import {RecipePreview} from './RecipePreview.jsx';
import {compileSubTemplate,nativeEntry} from './subtemplate-model.mjs';
import {validateEngineId,replaceLayerResource,layerGroups} from './flower-layer-model.mjs';
import {resourceLibrary,roleNames} from './library-model.mjs';
import {updateFan,resizeFan,orderFan} from './recipe-geometry.mjs';

const groupTitle={burst:'球花层',trail:'尾缀层',fan:'扇形单束'};
function LayerFields({entry,index,resources,change,onReplace,onRemove,removable}){
 const n=entry.native,set=(group,axis,value)=>change(d=>{d.entries[index].native[group][axis]=value});
 return <><label className="recipe-field"><span>关联基础模板</span><select aria-label={'第 '+(index+1)+' 层基础模板'} value={n.FXResourceId} onChange={e=>onReplace(resources.find(r=>r.id===e.target.value))}><option value={n.FXResourceId}>{n.FXResourceId}</option>{resources.filter(r=>r.role===entry.role&&r.id!==n.FXResourceId).map(r=><option value={r.id} key={r.key}>{r.label||r.name||r.id} · {r.platforms?.join('/')||'节目内'}</option>)}</select></label>
 <Field label="资源英文ID" type="text" value={n.FXResourceId} onChange={v=>change(d=>{d.entries[index].native.FXResourceId=v;delete d.entries[index].baseTemplateRef})}/>
 <Field label="发射延迟 s" min={0} value={n.LocalTimeOffset} onChange={v=>change(d=>d.entries[index].native.LocalTimeOffset=v)}/>
 <Field label="高度 Z m" value={n.PositionOffset.Z/100} onChange={v=>set('PositionOffset','Z',v===''?'':v*100)}/>
 <div className="recipe-grid">{['X','Y'].map(a=><Field key={a} label={'位置 '+a+' m'} value={n.PositionOffset[a]/100} onChange={v=>set('PositionOffset',a,v===''?'':v*100)}/>)}</div>
 <div className="layer-parameter-title">大小与角度</div><div className="recipe-grid">{['X','Y','Z'].map(a=><Field key={a} label={'大小 '+a+' 倍'} min={.001} value={n.EffectScale[a]} onChange={v=>set('EffectScale',a,v)}/>)}{['Pitch','Yaw','Roll'].map(a=><Field key={a} label={'角度 '+a+' °'} value={n.RotationOffset[a]} onChange={v=>set('RotationOffset',a,v)}/>)}</div>
 <details className="layer-random"><summary>随机范围 · 位置 / 角度 / 大小</summary><p className="field-hint">保留引擎的范围值，预览不重新抽样。位置以米显示，交付以厘米输出。</p><div className="recipe-grid">{['X','Y','Z'].map(a=><Field key={a} label={'位置随机 '+a+' ±m'} min={0} value={n.RandomPositionRange[a]/100} onChange={v=>set('RandomPositionRange',a,v===''?'':v*100)}/>)}{['Pitch','Yaw','Roll'].map(a=><Field key={a} label={'角度随机 '+a+' ±°'} min={0} value={n.RandomRotationRange[a]} onChange={v=>set('RandomRotationRange',a,v)}/>)}</div><Field label="大小随机 ±%" min={0} max={100} value={n.RandomScaleRatio*100} onChange={v=>change(d=>d.entries[index].native.RandomScaleRatio=v===''?'':v/100)}/><button onClick={()=>change(d=>{const x=d.entries[index].native;x.RandomPositionRange={X:0,Y:0,Z:0};x.RandomRotationRange={Pitch:0,Yaw:0,Roll:0};x.RandomScaleRatio=0})}>清零本层随机</button></details>
 <details><summary>平台与质量准入</summary><Field label="平台标记 PlatformFlags" min={0} max={255} step={1} value={n.Filter.PlatformFlags} onChange={v=>set('Filter','PlatformFlags',v)}/><Field label="最低画质（引擎枚举）" type="text" value={n.Filter.MinQualityLevel} onChange={v=>set('Filter','MinQualityLevel',v)}/><p className="field-hint">保留引擎枚举原值。未知枚举请在引擎确认后填写。</p></details>
 <details><summary>预览标定 · 不参与原生参数</summary>{[['heightM','资源原高 m'],['diameterM','资源原径 m'],['durationS','可见时长 s']].map(([key,label])=><Field key={key} label={label} min={0} value={entry.preview[key]} onChange={v=>change(d=>d.entries[index].preview[key]=v)}/>)}<Field label="预览颜色" type="color" value={entry.preview.color||'#efce87'} onChange={v=>change(d=>d.entries[index].preview.color=v)}/><label className="recipe-check"><input type="checkbox" checked={entry.preview.verified===true} onChange={e=>change(d=>d.entries[index].preview.verified=e.target.checked)}/>以上尺寸、时长已在UE实测</label></details>
 <button className="danger-action" disabled={!removable} onClick={onRemove}><Trash size={15}/>删除本层</button></>;
}
export function FlowerLayerEditor({doc,templateId,drafts,setDrafts,onSave,onApply,onNew,onBack,notify,editable=true,readOnly=false,initialRow=-1,catalogue}){
 const t=doc.templateLibrary.find(t=>t.id===templateId)||doc.templateLibrary[0],saved=doc.subTemplateLibrary.find(s=>s.key===t.subTemplateRef),draft=drafts[t.id]||saved;
 readOnly=readOnly||!!t.workspaceResource;
 const [row,setRow]=useState(0),[error,setError]=useState(''),errorRef=useRef();
 useEffect(()=>{setRow(Math.max(0,initialRow));setError('')},[t.id,initialRow,readOnly]);useEffect(()=>{if(error)errorRef.current?.focus()},[error]);
 const index=Math.min(row,draft.entries.length-1),dirty=!!drafts[t.id],count=doc.cues.filter(c=>c.templateId===t.id&&doc.events.some(e=>e.cueId===c.id&&!e.recipeRef)).length;
 const resources=resourceLibrary(doc,catalogue),groups=layerGroups(draft),engineId=draft.engineId||draft.id;
 const change=fn=>{const d=structuredClone(draft);fn(d);setDrafts(v=>({...v,[t.id]:d}));setError('')},clear=()=>setDrafts(v=>{const n={...v};delete n[t.id];return n});
 const accept=next=>{setDrafts(v=>({...v,[t.id]:next}));setError('')},safe=fn=>{try{fn()}catch(e){setError(e.message)}};
 function add(role){const resource=resources.find(r=>r.role===role),prior=draft.entries.find(e=>e.role===role);if(!resource&&!prior){setError('没有可用的此类基础模板，请先导入含该资源的节目');return}change(d=>d.entries.push({id:'layer-'+Date.now(),role,native:nativeEntry(resource?.id||prior.native.FXResourceId),preview:structuredClone(resource?.preview||prior.preview)}));setRow(draft.entries.length)}
 const angles=draft.entries.map(e=>e.native.RotationOffset.Roll),spread=Math.max(...angles)-Math.min(...angles),center=(Math.max(...angles)+Math.min(...angles))/2,times=[...new Set(draft.entries.map(e=>e.native.LocalTimeOffset))].sort((a,b)=>a-b);
 return <><section className="stage-panel recipe-preview"><div className="panel-heading"><b>花型模板 · {draft.name}</b><span>{dirty?'未保存修改':saved.key}</span><button onClick={onBack}><ArrowLeft size={16}/>返回舞台</button></div><RecipePreview draft={draft} row={index} setRow={setRow}/></section>
 <aside className="inspector recipe-inspector"><div className="panel-heading"><b>{readOnly?'花型预览':'花型编辑'}</b><button disabled={!editable||!!t.workspaceResource} title={t.workspaceResource?'固定资源在烘焙器另存新修订':undefined} onClick={()=>onNew(t.id)}><Copy size={16}/>复制</button></div><div className="inspector-body">
 {!editable&&<p className="field-hint">中低配只调整参演点。使用左侧“切到高配编辑”修改三档共用花型。</p>}{t.workspaceResource?<p className="field-hint">固定交付修订 {t.workspaceResource.revisionId}。烟花制作参数在烘焙器更新；在此设置发射节奏。当前舞台为比例示意，资源配表映射和 UE 外观需核对。</p>:readOnly&&<p className="field-hint">正在预览。左侧底栏“编辑花型”打开同一对象的编辑状态。</p>}
 <fieldset disabled={!editable||readOnly} className="recipe-fields"><Field label="花型名称（中文）" type="text" value={draft.name} onChange={v=>change(d=>d.name=v)}/><Field label="英文ID（引擎）" type="text" value={engineId} onChange={v=>change(d=>d.engineId=v)}/><p className="field-hint">中文名用于工作台；英文ID用于新版本交付，旧版本引用保持。</p>
 {draft.category==='fan'&&<section className="layer-fan-controls"><h3>扇形整体结构</h3><Field label="束数" min={1} max={256} step={1} value={draft.entries.length} onChange={v=>safe(()=>accept(resizeFan(draft,v)))}/><Field label="展开角度 °" min={0} max={180} value={+spread.toFixed(3)} onChange={spread=>safe(()=>accept(updateFan(draft,{spread})))}/><Field label="整体倾角 °" value={+center.toFixed(3)} onChange={tilt=>safe(()=>accept(updateFan(draft,{tilt})))}/><label className="recipe-field"><span>发射顺序</span><select aria-label="花型发射顺序" value="source" onChange={e=>safe(()=>accept(orderFan(draft,e.target.value,times.length>1?times[1]-times[0]:.08)))}><option value="source">保留当前先后</option><option value="left">左 → 右</option><option value="right">右 → 左</option><option value="center-out">中心外扩</option><option value="outside-in">两端内收</option><option value="together">各束同发</option></select></label><Field label="束间间隔 s" min={0} value={times.length>1?+(times[1]-times[0]).toFixed(6):0} onChange={gap=>safe(()=>accept(updateFan(draft,{gap})))}/></section>}
 {groups.map(g=><section className="flower-layer-group" key={g.role}><h3>{groupTitle[g.role]} <small>{g.indices.length} 层</small><button className="quiet-btn" aria-label={'添加'+groupTitle[g.role]} onClick={()=>add(g.role)}><Plus size={14}/></button></h3>{g.indices.map(i=><details className="flower-layer" key={draft.entries[i].id} open={index===i} onToggle={e=>{if(e.currentTarget.open&&row!==i)setRow(i)}}><summary onClick={e=>{e.preventDefault();setRow(index===i?-1:i)}}><b>{roleNames[g.role]} {g.indices.indexOf(i)+1}</b><span>{draft.entries[i].native.LocalTimeOffset}s · {draft.entries[i].native.FXResourceId}</span></summary>{index===i&&<LayerFields entry={draft.entries[i]} index={i} resources={resources} change={change} onReplace={r=>safe(()=>accept(replaceLayerResource(draft,i,r)))} removable={draft.entries.length>1} onRemove={()=>{change(d=>d.entries.splice(i,1));setRow(Math.max(0,i-1))}}/>}</details>)}</section>)}
 <div className="pair-actions">{(draft.category==='fan'?['fan']:['burst','trail']).filter(role=>!groups.some(g=>g.role===role)).map(role=><button key={role} onClick={()=>add(role)}><Plus size={15}/>添加{groupTitle[role]}</button>)}</div>
 <details><summary>版本与来源</summary><label className="recipe-field"><span>固定版本</span><select aria-label="固定版本" value={saved.key} onChange={e=>safe(()=>{onApply(t.id,e.target.value);clear()})}>{doc.subTemplateLibrary.filter(s=>s.id===saved.id).map(s=><option key={s.key}>{s.key}</option>)}</select></label><p className="field-hint">保存应用 {count} 个直接引用片段；编排模板已绑定版本保持。来源：{saved.sourceIndex===undefined?'用户创建':'源条目 #'+saved.sourceIndex}。</p></details></fieldset>
 {error&&<p ref={errorRef} tabIndex={-1} role="alert" className="panel-warning">{error}</p>}</div>
 <div className="recipe-save"><button className="primary-action" disabled={!dirty||!editable||readOnly} onClick={()=>safe(()=>{if(!draft.name?.trim())throw Error('请填写花型名称');validateEngineId(engineId);compileSubTemplate(draft);onSave(t.id,{...draft,engineId});clear()})}>保存新版本 · 应用 {count} 个片段</button><button disabled={!dirty} onClick={()=>{clear();setError('');notify('已放弃未保存修改')}}>放弃修改</button></div></aside></>;
}
