import {LaunchJitterControls} from './LaunchJitterControls.jsx';
import React,{useState,useRef,useEffect,useMemo} from 'react';
import {Copy,Trash,Plus,ArrowLeft,Play,Pause,ArrowCounterClockwise} from '@phosphor-icons/react';
import {RecipeField as Field} from './SubTemplateWorkspace.jsx';
import {compatiblePoints,validatePattern,quantizeCall} from './choreography-model.mjs';
import {buildPatternPreview,replacePatternTemplate} from './pattern-preview.mjs';
import {stamp} from './Timeline.jsx';
const clone=x=>structuredClone(x),orders=[['together','同时发射'],['left','左→右'],['right','右→左'],['center-out','中心外扩'],['outside-in','两端内收']];
export function ChoreographyEditor({doc,pattern,draft,onChange,onSave,onPlace,onCopy,onDelete,onBack,markers,time,tier,readOnly=false,single=false,onDiscard,onBeginEdit,onVersion,uses=[],onRevealInstance}){
 const current=draft||pattern,[callIndex,setCallIndex]=useState(0),[anchor,setAnchor]=useState(quantizeCall(time)),[alignment,setAlignment]=useState('launch'),[entryIndex,setEntryIndex]=useState(0),[error,setError]=useState(''),[previewTime,setPreviewTime]=useState(0),[play,setPlay]=useState(false),[zone,setZone]=useState(null),[anchorChoice,setAnchorChoice]=useState('head'),[previewScope,setPreviewScope]=useState('all'),[changeNotice,setChangeNotice]=useState(''),[removedCalls,setRemovedCalls]=useState(null),[flowerScope,setFlowerScope]=useState('current'),[flowerBefore,setFlowerBefore]=useState(null),[flowerError,setFlowerError]=useState('');
 const index=Math.min(callIndex,current.calls.length-1),call=current.calls[index],t=doc.templateLibrary.find(t=>t.id===call.templateId),recipe=doc.subTemplateLibrary.find(s=>s.key===call.recipeRef),launchZone=zone||t?.zone||'dam',dirty=!!draft,editable=tier==='high'&&!readOnly,canvas=useRef(),hits=useRef([]);
 useEffect(()=>{setCallIndex(0);setEntryIndex(0);setZone(null);setError('');setFlowerError('');setPreviewTime(0);setPlay(false);setAnchor(quantizeCall(time));setAnchorChoice('head');setPreviewScope('all');setChangeNotice('');setRemovedCalls(null);setFlowerScope('current');setFlowerBefore(null)},[pattern.id]);
 useEffect(()=>{setEntryIndex(0);setZone(null);setError('');setFlowerError('');setPreviewTime(0);setPlay(false);setRemovedCalls(null);setChangeNotice('');setFlowerScope('current');setFlowerBefore(null)},[pattern.key]);
 const change=fn=>{const next=clone(current);fn(next,next.calls[index]);onChange(next);setError('');setFlowerError('');setPlay(false);setPreviewTime(0)};
 const placement={anchorShowS:Number(anchor),alignment,alignedEntryIndex:Number(entryIndex),alignedCallIndex:index};
 const validationError=useMemo(()=>{try{validatePattern(doc,current,true);return ''}catch(e){return e.message}},[doc,current]);
 const computed=useMemo(()=>{try{return buildPatternPreview(doc,current,{scope:previewScope,callId:call.id,tier})}catch(e){return {error:e.message,begin:0,end:1,events:[],preview:{events:[],templates:doc.templateLibrary}}}},[doc,current,previewScope,call.id,tier]);
 useEffect(()=>{setPreviewTime(0);setPlay(false)},[previewScope,call.id,tier]);
 function selectCall(i){setFlowerScope('current');setCallIndex(i);setEntryIndex(0);setZone(null);setChangeNotice('');setError('')}
 function retainCurrent(){setRemovedCalls(clone(current.calls));change(d=>d.calls=[clone(call)]);setCallIndex(0);setChangeNotice('草稿仅保留当前调用，保存后生效；可恢复刚移除的调用。')}
 function removeCurrent(){setRemovedCalls(clone(current.calls));change(d=>d.calls.splice(index,1));setCallIndex(Math.max(0,index-1));setChangeNotice(`已移除第 ${index+1} 次调用的花型、点位和时序；保存后生效，可恢复。`)}
 function restoreRemoved(){const keep=new Map(current.calls.map(c=>[c.id,c]));change(d=>d.calls=[...removedCalls.map(c=>clone(keep.get(c.id)||c)),...current.calls.filter(c=>!removedCalls.some(v=>v.id===c.id))]);setRemovedCalls(null);setChangeNotice('已恢复刚移除的调用。')}
 useEffect(()=>{if(!play)return;let last=performance.now(),id;const tick=n=>{setPreviewTime(t=>{const value=t+(n-last)/1000;if(value>=computed.end){setPlay(false);return computed.end}return value});last=n;id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[play,computed.end]);
 useEffect(()=>{const c=canvas.current;const draw=()=>{if(!c.clientWidth||!c.clientHeight)return;hits.current=window.Stage17.render(c,{points:doc.points,events:computed.preview.events,templates:computed.preview.templates,time:computed.begin+previewTime,fixedCamera:true,cameraMode:'full',cameraZoom:1,view:'front',stage:doc.stage,selectedPointIds:tier==='high'?call.pointIds:call.profiles[tier],selectedEventIds:[]}).points};draw();const ro=new ResizeObserver(draw);ro.observe(c);return()=>ro.disconnect()},[doc,computed,previewTime,call,tier]);
 const available=t?compatiblePoints(doc,t):[];
 function toggle(id,q='high'){change((d,c)=>{const ids=q==='high'?c.pointIds:c.profiles[q],next=ids.includes(id)?ids.filter(p=>p!==id):[...ids,id];if(q==='high'){c.pointIds=next;for(const tier of ['medium','low'])c.profiles[tier]=[...new Set([...c.profiles[tier].filter(id=>next.includes(id)),...(!ids.includes(id)?[id]:[])])]}else c.profiles[q]=next})}
 function pick(e){if(!editable)return;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,hit=hits.current.map(p=>({...p,d:Math.hypot(x-p.x,y-p.y)})).filter(p=>p.d<=p.r+5).sort((a,b)=>a.d-b.d)[0];if(!hit)return;if(!available.includes(hit.id)){setError('此发射口与当前固定花型不兼容，请在右栏选择对应花型');return}setZone(doc.points.find(p=>p.id===hit.id).zone);toggle(hit.id)}
 const flowerGroups=useMemo(()=>{const groups=new Map();current.calls.forEach((c,i)=>{const key=c.templateId+':'+c.recipeRef;const group=groups.get(key)||{key,templateId:c.templateId,recipeRef:c.recipeRef,name:doc.templateLibrary.find(t=>t.id===c.templateId)?.name||'待绑定花型',indexes:[]};group.indexes.push(i);groups.set(key,group)});return [...groups.values()]},[doc,current]);
 const mixedFlowers=new Set(current.calls.map(c=>c.templateId)).size>1,uniformBinding=flowerGroups.length===1;
 function applyFlower(id,scope=flowerScope,ref){try{
  const next=replacePatternTemplate(doc,current,{scope,callId:call.id,templateId:id,recipeRef:ref});
  if(scope==='all')setFlowerBefore(clone(current));else setFlowerBefore(null);
  if(single)next.name=doc.templateLibrary.find(t=>t.id===id).name;
  onChange(next);setError('');setFlowerError('');setPlay(false);setPreviewTime(0);setEntryIndex(0);setZone(doc.templateLibrary.find(t=>t.id===id).zone);
  if(scope==='all'){setFlowerScope('all');setPreviewScope('all')}
  const name=doc.templateLibrary.find(t=>t.id===id).name;
  setChangeNotice(scope==='all'?`整套 ${next.calls.length} 次调用已统一为${name}；点位、时序和随机错开保留。保存后生效。`:`仅第 ${index+1} 次调用改为${name}；其它 ${next.calls.length-1} 次保持。`);
 }catch(e){setFlowerError(e.message);setChangeNotice('')}}
 function restoreFlower(){onChange(clone(flowerBefore));setFlowerBefore(null);setZone(null);setEntryIndex(0);setError('');setFlowerError('');setPreviewTime(0);setPlay(false);setFlowerScope('current');setChangeNotice('已恢复整套换花型前的草稿。')}
 function chooseAnchor(value){setAnchorChoice(value);if(value==='custom')return;if(value==='head')setAnchor(quantizeCall(time));else if(value.startsWith('section:'))setAnchor(quantizeCall(doc.sections.find(s=>s.id===value.slice(8)).start));else setAnchor(quantizeCall(markers.find(m=>m.id===value.slice(7)).time))}
 return <><section className="stage-panel recipe-preview"><div className="panel-heading"><b>{single?'发射编排':'编排模板'} · {current.name}</b><span>{single?'固定花型版本':dirty?pattern.key?'未保存修改':'新模板 · 未入库':'固定 v'+pattern.version}</span><button onClick={onBack}><ArrowLeft size={16}/>返回舞台</button></div>
 <div className="pattern-preview-scope"><div className="segmented" role="group" aria-label="编排模板预览范围"><button aria-pressed={previewScope==='all'} onClick={()=>setPreviewScope('all')}>全部调用 · {current.calls.length}</button><button aria-pressed={previewScope==='current'} onClick={()=>setPreviewScope('current')}>当前调用 · {index+1}</button></div><span role="status">{computed.error?'待配置':computed.empty?'本档无参演点':`${computed.events.length} 次发射`} · 仅预览本模板</span></div>
 <div className="pattern-flower-summary" aria-label="本模板实际花型"><b>{mixedFlowers?'混合花型':current.calls.some(c=>!c.templateId)?'待绑定花型':'整套花型'} · {new Set(current.calls.map(c=>c.templateId)).size} 种</b><div>{flowerGroups.map(g=><button key={g.key} aria-label={`查看花型 ${g.name}的调用`} onClick={()=>{selectCall(g.indexes[0]);setPreviewScope('current')}}>{g.name.replace(/^坝顶·|^前台·/,'')}<small>{g.indexes.length} 次 · {g.recipeRef||'未绑定'}</small></button>)}</div></div>
 <canvas className="recipe-canvas" ref={canvas} onClick={pick} aria-label="编排预览；点击兼容发射口选择"/>
 <div className="recipe-play"><button aria-label="重播编排模板" disabled={!!computed.error||computed.empty} onClick={()=>{setPreviewTime(0);setPlay(true)}}><ArrowCounterClockwise size={18}/></button><button aria-label={play?'暂停编排模板':'播放编排模板'} disabled={!!computed.error||computed.empty} onClick={()=>{if(previewTime>=computed.end)setPreviewTime(0);setPlay(v=>!v)}}>{play?<Pause size={18}/>:<Play size={18}/>}</button><input aria-label="编排模板局部播放头" type="range" min={0} max={computed.end} step={.01} value={Math.min(previewTime,computed.end)} onChange={e=>{setPlay(false);setPreviewTime(+e.target.value)}}/><output>{previewTime.toFixed(2)} / {computed.end.toFixed(2)} s</output></div>
 <div className="pattern-calls-heading">调用列表 · {current.calls.length} 次<span>右栏只编辑选中的一条</span></div>
 <div className="pattern-call-list" aria-label="编排模板调用列表">{current.calls.map((c,i)=>{const flower=doc.templateLibrary.find(t=>t.id===c.templateId);return <button key={c.id} aria-label={`选择调用 ${i+1} · ${flower?.name||'待绑定花型'}`} aria-pressed={index===i} onClick={()=>selectCall(i)}><span><b>{i+1} · {flower?.name||'待绑定花型'}</b><small>{c.recipeRef||'待选固定版本'} · {c.pointIds.join(' · ')||'待选发射口'}</small><small>名称：{c.label}</small></span><span>相对 {c.offsetS>=0?'+':''}{c.offsetS}s<small>{c.preserveSourceTiming?'保留提取时序':orders.find(o=>o[0]===c.order)?.[1]}</small></span></button>})}</div>
 {computed.state&&<div className="launch-step-preview" aria-label="实际发射时序">{computed.events.map(e=><span key={e.id}>{e.pointId} · {stamp(e.effectiveLaunch-computed.begin,true)}</span>)}</div>}
 <p id="placement-error" className="recipe-note" role={computed.error?'alert':undefined}>{current.calls.some(c=>!c.templateId)?'这是预置框架：先点右栏“配置编排模板”，选择花型和发射口，再保存。':computed.error||(computed.empty?'当前档位未选择参演点，预览为空；切高配设置三档点集。':'预览读取固定版本；花型内部延迟保留原精度。前台原生高度及UE包络待标定。')}</p></section>
 <aside className="inspector recipe-inspector"><div className="panel-heading"><b>{single?'发射编排':readOnly?'编排模板预览':'编排模板编辑'}</b>{!single&&<button disabled={tier!=='high'} onClick={()=>onCopy(current)}><Copy size={16}/>复制整套 · {current.calls.length} 次调用</button>}</div><div className="inspector-body">
 {!single&&<div className="pattern-version-state"><span>{dirty?pattern.key?'修改后保存为新版本':'新模板尚未入库':'已保存 v'+pattern.version}</span>{(doc.choreographyLibrary||[]).filter(p=>p.id===pattern.id).length>1&&<select aria-label="编排模板版本" value={pattern.key} onChange={e=>onVersion(e.target.value)}>{doc.choreographyLibrary.filter(p=>p.id===pattern.id).map(p=><option key={p.key} value={p.key}>固定 v{p.version}</option>)}</select>}{readOnly&&<button disabled={tier!=='high'} onClick={onBeginEdit}>{current.calls.every(c=>c.templateId&&c.pointIds.length)?'编辑并保存新版':'配置编排模板'}</button>}</div>}
 {!single&&<div className="pattern-current-call"><label className="recipe-field"><span>当前调用 · {index+1} / {current.calls.length}</span><select aria-label="当前编辑调用" value={index} onChange={e=>selectCall(+e.target.value)}>{current.calls.map((c,i)=><option key={c.id} value={i}>{i+1} · {doc.templateLibrary.find(t=>t.id===c.templateId)?.name||'待绑定花型'} · {c.pointIds.join('/')||'待选发射口'}</option>)}</select></label><p className="field-hint">点位和节奏只修改这一条；花型按下方应用范围设置。保存和创建片段包含全部 {current.calls.length} 次调用。</p></div>}
 {changeNotice&&<p role="status" className="pattern-change-notice">{changeNotice}</p>}
 <fieldset disabled={!editable} className="recipe-fields"><Field label={single?'片段名称':'编排模板名称'} type="text" value={current.name} onChange={v=>change(d=>d.name=v)}/>
 {!single&&<><h3>当前调用设置</h3><Field label="调用名称（仅作标记）" type="text" value={call.label} onChange={v=>change((d,c)=>c.label=v)}/><div className="pattern-call-removal"><p className="field-hint">改名或清空名称不会移除花型引用。</p><button className="quiet-btn" disabled={current.calls.length===1} onClick={removeCurrent}><Trash size={16}/>删除当前调用</button></div></>}
 <label className="recipe-field"><span>发射区域</span><select aria-label="发射区域" value={launchZone} onChange={e=>{const value=e.target.value;setZone(value);change((d,c)=>{c.pointIds=c.pointIds.filter(id=>doc.points.find(p=>p.id===id)?.zone===value);for(const q of ['medium','low'])c.profiles[q]=c.profiles[q].filter(id=>c.pointIds.includes(id))})}}><option value="dam">坝顶 · P主花 / B扇形</option><option value="front">小平台 · F发射口</option></select></label>
 {call.eventAdjustments&&<div><p className="field-hint">保留源片段微调：缩放 {call.eventAdjustments.scale??1}× · 高度偏移 {call.eventAdjustments.dz??0} m · 角度 {call.eventAdjustments.tilt??0}°。替换花型时重置这些偏移。</p><button className="quiet-btn" onClick={()=>{change((d,c)=>delete c.eventAdjustments);setChangeNotice('已重置当前调用的源片段微调，使用花型固定版本的参数。其它调用保持。')}}>重置源片段微调</button></div>}
 {t?.zone!==launchZone&&<p className="panel-warning">当前花型没有此区域的兼容版本，请明确选择下方花型；不会自动缩放替换。</p>}
 <section className="pattern-flower-application" aria-label="花型应用设置">
 {!single&&<><span className="field-label">花型应用范围</span><div className="segmented" role="group" aria-label="花型应用范围"><button aria-pressed={flowerScope==='current'} onClick={()=>setFlowerScope('current')}>只改这一条</button><button aria-pressed={flowerScope==='all'} onClick={()=>setFlowerScope('all')}>整套统一</button></div><p className="field-hint">{flowerScope==='all'?`选择花型后，整套 ${current.calls.length} 次调用一起更换；每条点位和节奏保留。`:`只更换第 ${index+1} 次调用的花型；其它调用会继续播放。`}</p></>}
 <label className="recipe-field"><span>{flowerScope==='all'?'整套花型模板':'当前调用花型'}</span><select aria-label="调用花型" aria-describedby={flowerError?'pattern-flower-error':undefined} aria-invalid={!!flowerError} value={flowerScope==='all'&&!uniformBinding?'':call.templateId||''} onChange={e=>applyFlower(e.target.value)}>{flowerScope==='all'&&!uniformBinding?<option value="" disabled>当前混合 · 选择整套使用的花型</option>:!t?<option value="">请选择花型模板</option>:t.zone!==launchZone&&<option value={t.id}>{t.name} · 当前不兼容</option>}{doc.templateLibrary.filter(t=>t.zone===launchZone).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
 <label className="recipe-field"><span>{flowerScope==='all'?'整套固定版本':'当前调用固定版本'}</span><select aria-label="调用固定版本" disabled={flowerScope==='all'&&!uniformBinding} value={flowerScope==='all'&&!uniformBinding?'':call.recipeRef||''} onChange={e=>flowerScope==='all'?applyFlower(call.templateId,'all',e.target.value):change((d,c)=>c.recipeRef=e.target.value)}>{flowerScope==='all'&&!uniformBinding&&<option value="">先统一花型</option>}{doc.subTemplateLibrary.filter(s=>s.id===recipe?.id).map(s=><option key={s.key} value={s.key}>{s.key}</option>)}</select></label>
 {flowerError&&<p id="pattern-flower-error" role="alert" className="panel-warning">{flowerError} 未执行替换。</p>}
 {!single&&current.calls.length>1&&!uniformBinding&&t&&<button className="pattern-unify-btn" onClick={()=>applyFlower(call.templateId,'all',call.recipeRef)}>整套改用{t.name.replace(/^坝顶·|^前台·/,'')} · {current.calls.length} 次调用</button>}
 {!single&&flowerBefore&&<button className="quiet-btn" onClick={restoreFlower}>恢复整套换花型前的草稿</button>}
 {!single&&current.calls.length>1&&<button className="quiet-btn" onClick={retainCurrent}>只保留这一条 · 移除其它 {current.calls.length-1} 次调用</button>}
 {!single&&removedCalls&&<button className="quiet-btn" onClick={restoreRemoved}>恢复刚移除的调用</button>}
 </section>
 {['high','medium','low'].map(q=><details key={q} open={q==='high'}><summary>{q==='high'?'高配':q==='medium'?'中配':'低配'}发射口 · {(q==='high'?call.pointIds:call.profiles[q]).length} 点</summary>{(launchZone==='front'?['F']:['P','B']).map(group=><div key={group}><small>{group==='P'?'P · 主花':group==='B'?'B · 扇形':'F · 小平台'}</small><div className="point-tags">{doc.points.filter(p=>p.id.startsWith(group)).map(p=>{const selected=(q==='high'?call.pointIds:call.profiles[q]).includes(p.id),disabled=!available.includes(p.id)||(q!=='high'&&!call.pointIds.includes(p.id));return <button key={p.id} aria-label={`调用 ${q} ${p.id}`} aria-pressed={selected} title={!available.includes(p.id)?'当前花型与该发射口不兼容':q!=='high'&&!call.pointIds.includes(p.id)?'先加入高配点集':p.id} disabled={disabled} onClick={()=>toggle(p.id,q)}>{p.id}</button>})}</div></div>)}<p className="field-hint">{q==='high'?'选择实际发射口；不默认填满舞台。':'仅过滤高配已选点，保留共同发射时刻。'}</p></details>)}
 {!single&&<Field label="相对锚点 s" value={call.offsetS} onChange={v=>change((d,c)=>{c.offsetS=v;delete c.preserveSourceTiming})}/>}
 <label className="recipe-field"><span>点位顺序</span><select aria-label="调用点位顺序" value={call.order} onChange={e=>change((d,c)=>{c.order=e.target.value;c.gap=e.target.value==='together'?0:c.gap||.1})}>{call.order==='source'&&<option value="source">保留提取时序</option>}{orders.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><Field label="每步间隔 s" disabled={call.order==='together'} min={0} step={.1} value={call.gap} onChange={v=>change((d,c)=>c.gap=v)}/>
 <LaunchJitterControls value={call.launchJitter} disabled={!editable} onChange={value=>change((d,c)=>c.launchJitter=value)}/>
 {!single&&<div className="pair-actions"><button onClick={()=>{change(d=>d.calls.push({...clone(call),id:'call-'+Date.now(),label:'新调用',pointIds:[],profiles:{medium:[],low:[]},offsetS:0}));setCallIndex(current.calls.length);setZone(null)}}><Plus size={16}/>添加调用</button></div>}</fieldset>
 <div className="inspector-section"><h3>放入节目</h3><label className="recipe-field"><span>定位依据</span><select aria-label="编排定位依据" value={anchorChoice} onChange={e=>chooseAnchor(e.target.value)}><option value="head">当前播放头</option><option value="custom">指定节目秒数</option>{doc.sections.map(s=><option key={s.id} value={'section:'+s.id}>段落起点 · {s.name}</option>)}{markers.map(m=><option key={m.id} value={'marker:'+m.id}>音乐标记 · {m.label||m.name||m.id} · 待确认</option>)}</select></label><Field label="节目时刻 s" min={0} step={.1} value={anchor} onChange={v=>{setAnchor(v);setAnchorChoice('custom')}}/><p className="field-hint">{doc.meta.musicStatus==='none'?'尚未导入音乐，可直接按节目秒数编排。':Number(anchor)<(doc.meta.musicOffset??10)?'音乐尚未开始':'对应音乐 '+stamp(Number(anchor)-(doc.meta.musicOffset??10),true)}</p>
 <label className="recipe-field"><span>对齐目标</span><select aria-label="编排对齐方式" value={alignment} onChange={e=>setAlignment(e.target.value)}><option value="launch">开始发射</option><option value="entry">当前调用的指定层起播</option></select></label>{alignment==='entry'&&<label className="recipe-field"><span>当前调用的层</span><select aria-label="对齐资源层" value={entryIndex} onChange={e=>setEntryIndex(+e.target.value)}>{recipe?.entries.map((e,i)=><option key={e.id} value={i}>{i+1} · {e.role==='burst'?'球花':e.role==='fan'?'扇形':'尾缀'} · 延迟 {e.native.LocalTimeOffset}s</option>)}</select></label>}
 <p className="field-hint">对齐整组时只使用当前选定调用的层延迟，内部交叠保持；名义时间以0.1秒设置；随机错开追加到每次完整花型，实际时序显示在预览下方。</p></div>{!single&&<section className="pattern-uses inspector-section" aria-label="模板在节目中的引用"><h3>节目中的引用 <span>{uses.length} 组 · {uses.reduce((n,g)=>n+g.cueIds.length,0)} 片段</span></h3>{uses.length?uses.map(g=><button className="pattern-use-row" key={g.id} onClick={()=>onRevealInstance(g)}><span>{stamp(g.start,true)} · {g.cueIds.length} 片段<small>固定 v{doc.choreographyLibrary.find(p=>p.key===g.key)?.version||'?'}</small></span><span>定位 ↗</span></button>):<p className="field-hint">尚未放入节目。设置时刻后创建片段，时间轴会显示这组引用。</p>}</section>}{error&&<p role="alert" className="panel-warning">{error}</p>}</div>
 <div className="recipe-save pattern-save">{validationError&&<p id="pattern-save-error" className="panel-warning">全部调用尚未配置完整：{validationError}</p>}{!single&&dirty&&!readOnly&&<div className="pair-actions"><button disabled={tier!=='high'||!!validationError} onClick={()=>{try{onSave(current);setError('')}catch(e){setError(e.message)}}}>仅保存编排模板 · {current.calls.length} 次调用</button><button onClick={()=>{setZone(null);setError('');setFlowerError('');setChangeNotice('');setRemovedCalls(null);setFlowerScope('current');setFlowerBefore(null);setPreviewTime(0);setPlay(false);onDiscard()}}>放弃修改</button></div>}<button className="primary-action" disabled={tier!=='high'||!!validationError} aria-describedby={validationError?'pattern-save-error':undefined} onClick={()=>{try{onPlace(current,{...placement,sectionId:anchorChoice.startsWith('section:')?anchorChoice.slice(8):null})}catch(e){setError(e.message)}}}>{!single&&dirty?'保存模板并创建片段':'创建编排片段'}{!single&&' · '+current.calls.length+' 次调用'}</button>{!single&&<small className="field-hint">{dirty?'保存后模板入库，片段引用该固定版本。':'引用固定 v'+pattern.version+'；每次放入节目生成独立的一组。'}</small>}{!single&&!pattern.builtin&&pattern.key&&<button className="quiet-btn" disabled={tier!=='high'} onClick={()=>onDelete(pattern.id)}>删除编排模板 · 可撤销</button>}</div></aside></>;
}
