import React,{useState,useRef,useEffect} from 'react';
import {DownloadSimple,UploadSimple,MusicNotes} from '@phosphor-icons/react';
import {PanelHeader} from './DeliveryPanel.jsx';
import {RecipeField as Field} from './SubTemplateWorkspace.jsx';
import {AsyncButton} from './InteractionFeedback.jsx';
import {makeBackup} from './workbench-data.mjs';
import {newProgram,preflightProject,readMusicFile} from './program-project.mjs';
export function ProgramPanel({state,seed,mode,onSwitch,onBack,onImport,onSave,onExport,onPendingMetadata,onMetadata,onMusic,onRemoveMusic,onRecover,onClear,notify}){
 const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false}},[]);
 const [name,setName]=useState(mode==='new'?'我的烟花节目':state.doc.meta.programName||state.doc.meta.name||'烟花节目'),[duration,setDuration]=useState(mode==='new'?120:state.doc.meta.duration),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(mode==='backup')onPendingMetadata({programName:name,name,duration:Number(duration)});return()=>onPendingMetadata(null)},[mode,name,duration,onPendingMetadata]);
 useEffect(()=>{if(mode==='backup'){setName(state.doc.meta.programName||state.doc.meta.name||'烟花节目');setDuration(state.doc.meta.duration)}},[mode,state.doc.meta.programId,state.doc.meta.programName,state.doc.meta.name,state.doc.meta.duration]);
 async function open(e){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{if(file.size>128*1024*1024)throw Error('节目文件不能超过128MB');const raw=await file.text(),next=preflightProject(raw,seed);if(next.audioRef?.kind==='embedded'){const bytes=await fetch(next.audioRef.dataUrl).then(r=>r.arrayBuffer()),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==next.audioRef.sha256)throw Error('音频校验不一致，当前节目未改变')}if(active.current){onImport(next);notify('节目已打开，可撤销')}}catch(e){setError(e.message)}finally{setBusy(false);e.target.value=''}}
 async function music(e){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const result=await readMusicFile(file);if(active.current){onMusic(result)}}catch(e){setError(e.message)}finally{setBusy(false);e.target.value=''}}
 return <><PanelHeader title="节目管理" onBack={onBack}/><div className="inspector-body programme-body"><div className="programme-commands" role="group" aria-label="节目操作">{[['new','新建节目'],['open','打开节目'],['saveas','另存为'],['backup','备份与恢复']].map(([id,label])=><button key={id} disabled={busy} aria-pressed={mode===id} onClick={()=>onSwitch(id)}>{label}</button>)}</div>
 {mode==='new'?<><h2>新建空白节目</h2><p className="field-hint">保留模板库与舞台点位。新节目没有音乐、段落或片段；当前节目可撤销恢复。</p><Field label="新节目名称" type="text" value={name} onChange={setName}/><Field label="节目时长 s" value={duration} min={10} max={3600} onChange={setDuration}/><button className="primary-action full" onClick={()=>{try{onImport(newProgram(state,{name,duration:Number(duration)}));notify('空白节目已创建，可撤销')}catch(e){setError(e.message)}}}>创建空白节目</button><button className="full" onClick={onClear}>清空编排，保留音乐</button></>:mode==='open'?<><h2>打开节目</h2><p className="field-hint">节目文件或旧完整备份先校验，再原子替换。文件错误不会改变当前内容，成功打开可撤销。</p><label className="file-action"><UploadSimple size={16}/>{busy?'正在校验…':'选择节目版本文件'}<input aria-label="打开节目文件" type="file" accept=".json,.dfshow,application/json" disabled={busy} onChange={open}/></label></>:<><h2>{mode==='saveas'?'另存为新节目':'保存与恢复'}</h2><Field label="节目名称" type="text" value={name} onChange={setName}/><Field label="节目时长 s" min={10} max={3600} value={duration} onChange={setDuration}/><AsyncButton className="full" pendingLabel="保存中…" onClick={()=>onSave({programName:name,name,duration:Number(duration)})}>保存节目</AsyncButton><AsyncButton className="primary-action full" pendingLabel="正在打包…" disabled={busy} onClick={()=>onExport({programName:name,name,duration:Number(duration)},mode==='saveas')}><DownloadSimple size={16}/>{mode==='saveas'?'另存为节目文件':'下载节目版本文件'}</AsyncButton><p className="field-hint">保存写入当前浏览器；下载版本文件用于转移或备份，包含片段、固定模板版本、三档和段落；已导入的音乐也随节目文件保存。节目文件版本用于恢复整场；模板版本用于复用花型与编排。</p><AsyncButton className="full" onClick={onRecover}>恢复切换前节目 · 可撤销</AsyncButton><button className="full" onClick={()=>onImport(seed)}>恢复初始方案 · 可撤销</button><details><summary>查看完整备份内容</summary><textarea aria-label="完整节目备份" readOnly value={JSON.stringify(makeBackup(state,seed))}/></details></>}
 <section className="inspector-section"><h3>节目音乐</h3><p>{state.doc.meta.musicStatus==='none'?'尚未导入音乐':state.musicData?.title||state.doc.meta.musicTitle||'原节目音乐'}</p><p className="field-hint">{state.doc.meta.musicStatus!=='none'&&!state.audioRef?'未附音频，当前波形与段落是原曲的节奏参考。导入原曲可保留关联；换曲会解除旧音乐锚点。':'导入后显示波形，不自动创建语义段落。没有音乐也能编排和交付。'}</p><label className="file-action"><MusicNotes size={16}/>{busy?'正在读取…':'导入或替换音乐'}<input aria-label="导入音乐文件" disabled={busy} type="file" accept="audio/*,.wav,.mp3,.ogg,.m4a" onChange={music}/></label>{state.doc.meta.musicStatus!=='none'&&<><Field label="音乐起播时刻 s" min={0} value={state.doc.meta.musicOffset??10} onChange={v=>{try{onMetadata({musicOffset:v})}catch(e){setError(e.message)}}}/><p className="field-hint">调整音乐起点只带动已关联音乐的片段与标记；按节目秒数放置的片段及编排段落保持原位。</p><button className="full" onClick={onRemoveMusic}>移除音乐，保留片段时刻</button></>}</section>
 {error&&<p className="panel-warning" role="alert">{error}</p>}</div></>;
}
