import React,{useState,useRef,useEffect} from 'react';
import {PencilSimple,Plus,MagnifyingGlass,Stack,Play,CheckCircle} from '@phosphor-icons/react';
import {drawRecipeThumbnail} from './recipe-thumbnail.mjs';
import {resourceLibrary,sizeTip,patternTip,roleNames,matchesLibrarySearch} from './library-model.mjs';
import {patternInstances} from './pattern-linkage.mjs';
import {latestPatterns} from './choreography-model.mjs';
function Thumbnail({t,r}){const ref=useRef();useEffect(()=>{if(r&&ref.current)drawRecipeThumbnail(ref.current,t,r)},[t,r]);const source=t.workspaceResource;if(source?.thumbnail?.status==='ready')return <img className="thumb" alt={t.name+' 固定修订回放'} src={'http://127.0.0.1:8034/api/deliveries/'+source.deliveryId+'/'+source.thumbnail.file}/>;return <canvas ref={ref} className="thumb" aria-label={t.name}/>}
export function TemplateLibrary({doc,kind,onKind,selection,onSelect,onEdit,onAdd,onCreate,spec,catalogue,tier,onSwitchHigh,reveal,draftName}){
 const listRef=useRef(),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[zone,setZone]=useState('all');
 useEffect(()=>{const list=listRef.current;if(!list)return;const reveal=()=>{const selected=list.querySelector('.chosen');if(!selected)return;const a=list.getBoundingClientRect(),b=selected.getBoundingClientRect();if(b.top<a.top)list.scrollTop-=a.top-b.top;else if(b.bottom>a.bottom)list.scrollTop+=b.bottom-a.bottom};const observer=new ResizeObserver(reveal);observer.observe(list);return()=>observer.disconnect()},[selection,kind]);
 useEffect(()=>{setSearch('');setCategory('all');setZone('all')},[reveal]);
 const items=kind==='flowers'?doc.templateLibrary.map(t=>{const r=doc.subTemplateLibrary.find(s=>s.key===t.subTemplateRef);return {id:t.id,name:t.name,category:r.category,t,r,tip:sizeTip(t,r,spec),subtitle:r.entries.length+' 层 · v'+r.version}}):kind==='patterns'?latestPatterns(doc).map(p=>({id:p.id,name:p.name,category:'pattern',p,tip:patternTip(doc,p,spec),subtitle:(!p.calls.every(c=>c.templateId&&c.recipeRef)?'预置框架 · ':'')+p.calls.length+' 次调用 · v'+p.version+' · '+patternInstances(doc,p.id).length+' 组引用'})):resourceLibrary(doc,catalogue).map(a=>({id:a.key,name:a.label||a.name,category:a.role==='burst'?'ball':a.role,a,tip:{tag:(roleNames[a.role]||'待确认')+' · '+({small:'小',medium:'中',large:'大'}[a.sizeClass]||'待标定'),detail:'ResourceFXTable只读目录；实际尺寸待引擎标定'},subtitle:a.platforms?.join(' / ')||'节目内资源'}));
 const visible=items.filter(i=>(category==='all'||category===i.category)&&matchesLibrarySearch(i,search)&&(zone==='all'||!i.t||i.t.zone===zone));
 const chosen=items.find(i=>i.id===selection),disabled=tier!=='high'||!chosen;
 return <><div className="library-kinds tabs">{[['assets','基础模板'],['flowers','花型模板'],['patterns','编排模板']].map(([id,label])=><button key={id} aria-pressed={kind===id} aria-current={kind===id?'page':undefined} onClick={()=>{onKind(id);setCategory('all')}}>{label}</button>)}</div>
 <label className="search"><MagnifyingGlass size={16}/><input aria-label="搜索模板库" placeholder="搜索名称或模板" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {kind!=='patterns'&&<div className="library-category" role="group" aria-label="花型类别">{[['all','全部'],['trail','尾缀'],['ball','球花'],['fan','扇形']].map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div>}
 <div className="library-filter"><select aria-label="模板适用区域" value={zone} onChange={e=>setZone(e.target.value)}><option value="all">全部区域</option><option value="dam">坝顶</option><option value="front">小平台</option></select><span>{visible.length} {kind==='patterns'?'模板':'个'}</span>{kind==='flowers'&&<button className="quiet-btn library-create" disabled={tier!=='high'} onClick={()=>onCreate(kind)}><Plus size={14}/>新建</button>}</div>
 {kind==='patterns'&&<><div className="pattern-create-row"><button className="primary-action pattern-create" disabled={tier!=='high'} title={tier!=='high'?'切到高配后可新建共用模板':undefined} onClick={()=>onCreate(kind)}><Plus size={18}/>新建编排模板</button></div><p className="field-hint pattern-library-hint">先保存编排模板，再设置节目时刻，生成引用片段。</p></>}
 <div ref={listRef} className="library-list template-items compact-template-items">{visible.map(i=><button key={i.id} className={'template-card template-select '+(selection===i.id?'chosen':'')} aria-pressed={selection===i.id} onClick={()=>onSelect(kind,i)} aria-label={'预览 '+i.name} title={i.name}>
 {i.t?<Thumbnail t={i.t} r={i.r}/>:i.a?<Thumbnail t={{name:i.name,color:i.a.entry.preview.color,kind:i.a.role==='fan'?'fan':'small'}} r={{entries:[i.a.entry]}}/>:<Stack size={28}/>}
 <span className="template-description"><b>{i.name.replace(/^坝顶·|^前台·/,'')}</b><small><span title={i.tip.detail}>{i.tip.tag}</span> · {i.subtitle}</small></span>{selection===i.id&&<CheckCircle className="template-selected-mark" size={18} weight="fill"/>}
 </button>)}{!visible.length&&<p className="empty">没有匹配结果<button onClick={()=>{setSearch('');setCategory('all');setZone('all')}}>清除筛选</button></p>}</div>
 {tier!=='high'&&<div className="library-edit-hint"><span>{tier==='low'?'低配':'中配'}预览 · 花型与节奏三档共用</span><button onClick={onSwitchHigh}>切到高配编辑</button></div>}
 <div className="selected-template-toolbar" role="group" aria-label="所选模板操作"><div className="selected-template-name">已选：<b title={chosen?.name}>{chosen?.name.replace(/^坝顶·|^前台·/,'')||draftName||'请选择模板'}</b></div><div className="pair-actions">{kind!=='assets'&&<button disabled={disabled||!!chosen?.t?.workspaceResource} title={tier!=='high'?'切到高配后可编辑':undefined} onClick={()=>onEdit(kind,chosen)}><PencilSimple size={16}/>{chosen?.t?.workspaceResource?'固定交付资源':kind==='patterns'?'编辑编排':kind==='assets'?'编辑来源':'编辑花型'}</button>}<button disabled={disabled||chosen?.a?.role==='unknown'} className="tonal-action" title={tier!=='high'?'切到高配后可编排':undefined} onClick={()=>onAdd(kind,chosen)}><Play size={16} weight="fill"/>{kind==='assets'?'用于花型':'设置发射'}</button></div></div></>;
}
