import {pointerTime} from './navigation.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {CaretRight,CaretDown,MusicNotes} from '@phosphor-icons/react';
export const stamp=(t,precise=false)=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}${precise?'.'+String(Math.floor((t%1+1e-8)*100)).padStart(2,'0'):''}`;
const launch=e=>e.effectiveLaunch??e.launch+(e.dt||0),end=e=>e.effectiveEnd??e.end+(e.dt||0);
export function Timeline({doc,music,structure,time,range,setRange,selected,onSelect,onPlayCue,onSeek,onScrubStart,onScrubEnd,selectedSection,energy,markers,musicMarkers,onSection,filter,point,onPoint,onPointDouble,solo,onRangeSection}){
 const [open,setOpen]=useState({P:false,B:false,F:true}),[width,setWidth]=useState(1000),[trackZone,setTrackZone]=useState('all');
 const ruler=useRef(),dragging=useRef(null),body=useRef(),wave=useRef(),tracks=useRef(),[gutter,setGutter]=useState(10),[hover,setHover]=useState(null),sectionDrag=useRef(null),[sectionSelection,setSectionSelection]=useState(null);
 const [a,b]=range,span=b-a,pct=t=>(t-a)/span*100,offset=doc.meta.musicOffset??10;
 useEffect(()=>{const ro=new ResizeObserver(entries=>{setWidth(entries[0].contentRect.width);if(tracks.current)setGutter(tracks.current.offsetWidth-tracks.current.clientWidth)});ro.observe(body.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{const el=wave.current,w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio,2);el.width=w*d;el.height=h*d;const c=el.getContext('2d');c.scale(d,d);c.clearRect(0,0,w,h);music.waveform.forEach((v,i)=>{const t=offset+i/music.waveform.length*music.duration;if(t<a||t>b)return;c.fillStyle=t<=time?'#9bcbbd':'#517d79';c.fillRect((t-a)/span*w,h/2-v*(h/2-5),Math.max(1,w/span*music.duration/music.waveform.length-.25),Math.max(1,v*(h-10)))});if(energy){c.strokeStyle='#e7bb77';c.lineWidth=1.7;c.beginPath();let started=false;structure.energy.forEach((v,i)=>{const t=offset+i*structure.energyStep;if(t<a||t>b)return;const x=(t-a)/span*w,y=h-7-v*(h-17);if(started)c.lineTo(x,y);else{c.moveTo(x,y);started=true}});c.stroke()}},[width,range,time,energy,music,structure]);
 useEffect(()=>{if(point){setOpen(o=>({...o,[point[0]]:true}));setTrackZone('all');const frame=requestAnimationFrame(()=>tracks.current?.querySelector(`[data-point="${point}"]`)?.scrollIntoView({block:'nearest'}));return()=>cancelAnimationFrame(frame)}},[point]);
 useEffect(()=>{if(!selected)return;const groups=new Set(selected.pointIds.map(id=>id[0]));setOpen(o=>({...o,...Object.fromEntries([...groups].map(g=>[g,true]))}));setTrackZone('all');requestAnimationFrame(()=>tracks.current?.querySelector(`[data-point="${selected.pointIds[0]}"]`)?.scrollIntoView({block:'nearest'}))},[selected?.id,selected?.pointIds.join('|')]);
 const bindSection={onPointerDown:e=>{if(e.button!==0||e.target.closest('button'))return;e.preventDefault();const r=ruler.current.getBoundingClientRect(),at=Math.round(pointerTime(e.clientX,r,range)*10)/10;sectionDrag.current={id:e.pointerId,start:at,rect:r};setSectionSelection([at,at]);e.currentTarget.setPointerCapture(e.pointerId)},onPointerMove:e=>{const d=sectionDrag.current;if(d?.id!==e.pointerId)return;const at=Math.round(pointerTime(e.clientX,d.rect,range)*10)/10;setSectionSelection([Math.min(at,d.start),Math.max(at,d.start)])},onPointerUp:e=>{const d=sectionDrag.current;if(d?.id!==e.pointerId)return;const at=Math.round(pointerTime(e.clientX,d.rect,range)*10)/10,r=[Math.min(at,d.start),Math.max(at,d.start)];sectionDrag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setSectionSelection(null);if(r[1]-r[0]>=.1)onRangeSection?.(r)},onPointerCancel:()=>{sectionDrag.current=null;setSectionSelection(null)}};
 const shownEvents=solo&&point?doc.events.filter(e=>e.pointId===point):doc.events;
 const eventGroups={P:shownEvents.filter(e=>e.pointId.startsWith('P')),B:shownEvents.filter(e=>e.pointId.startsWith('B')),F:shownEvents.filter(e=>e.pointId.startsWith('F'))};
 const interval=span>100?20:span>30?10:span>12?5:1,ticks=[];for(let t=Math.ceil(a/interval)*interval;t<=b;t+=interval)ticks.push(t);
 function pointerSeek(e){const d=dragging.current;onSeek(pointerTime(e.clientX,d?.rect||ruler.current.getBoundingClientRect(),d?.range||range))}
 function finishScrub(e,cancel=false){if(dragging.current?.id!==e.pointerId)return;if(!cancel)pointerSeek(e);dragging.current=null;onScrubEnd();if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 const bindSeek={onPointerDown:e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();dragging.current={id:e.pointerId,rect:ruler.current.getBoundingClientRect(),range:[...range]};e.currentTarget.setPointerCapture(e.pointerId);onScrubStart();pointerSeek(e)},onPointerMove:e=>{if(dragging.current?.id===e.pointerId)pointerSeek(e)},onPointerUp:e=>finishScrub(e),onPointerCancel:e=>finishScrub(e,true),onLostPointerCapture:e=>finishScrub(e,true),onKeyDown:e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();onSeek(Math.max(a,Math.min(b,time+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?1:.1))))}if(e.key==='Home'){e.preventDefault();onSeek(a)}if(e.key==='End'){e.preventDefault();onSeek(b)}}};
 const groups=[['P','坝顶 · 主花',9],['B','坝顶 · 扇形',8],['F','小平台',7]].filter(([g])=>(!solo||!point||point.startsWith(g))&&(trackZone==='all'||(trackZone==='front'?g==='F':g!=='F'))).map(([g,label,count])=>[g,label,solo&&point?1:count]);
 function bars(events,summary=false){if(summary){const bins=Array.from({length:240},(_,i)=>{const t=a+(i+.5)/240*span;return events.filter(e=>launch(e)<=t&&end(e)>=t).length}),max=Math.max(1,...bins);return <div className="density" aria-label="组内播放密度，展开查看片段">{bins.map((n,i)=><i key={i} style={{left:i/240*100+'%',height:(n?3+n/max*11:0)+'px',opacity:.25+n/max*.55}}/>)}</div>}return events.filter(e=>end(e)>=a&&launch(e)<=b).map(e=>{const cue=doc.cues.find(c=>c.id===e.cueId),t=doc.templateLibrary.find(t=>t.id===e.templateId),start=Math.max(a,launch(e)),finish=Math.min(b,end(e)),isSel=e.cueId===selected?.id;return <button key={e.id} className={'clip '+(summary?'summary-clip ':'')+(isSel?'clip-selected ':'')+(filter&&filter!==e.templateId?'clip-dim':'')} style={{left:pct(start)+'%',width:Math.max(.22,(finish-start)/span*100)+'%',minWidth:'12px',backgroundColor:t?.color||'#cba365'}} aria-pressed={isSel} title={`${cue?.name} · ${e.pointId} · ${stamp(launch(e),true)}–${stamp(end(e),true)}`} aria-label={`${e.pointId} ${cue?.name||t?.name} ${stamp(launch(e))}`} onClick={()=>onSelect(cue)} onDoubleClick={()=>onPlayCue(cue)} onMouseEnter={()=>setHover(`${e.pointId} · ${t?.name} · ${stamp(launch(e),true)} → ${stamp(end(e),true)}`)} onMouseLeave={()=>setHover(null)}>{<span>{cue?.name||short(t?.name||'')}</span>}</button>})}
 return <div className="timeline-content" style={{'--scrollbar':gutter+'px'}}>
 {span<doc.meta.duration-.1&&<div className="overview-row"><div className="track-label">全曲导航</div><div className="overview" onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),mid=(e.clientX-r.left)/r.width*doc.meta.duration,start=Math.max(0,Math.min(doc.meta.duration-span,mid-span/2));setRange([start,start+span])}} role="slider" tabIndex={0} aria-label="全曲导航窗口" aria-valuemin={0} aria-valuemax={doc.meta.duration-span} aria-valuenow={a} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const start=e.key==='Home'?0:e.key==='End'?doc.meta.duration-span:Math.max(0,Math.min(doc.meta.duration-span,a+(e.key==='ArrowRight'?1:-1)*span/4));setRange([start,start+span])}}}>{doc.sections.map(s=><span key={s.id} style={{left:s.start/doc.meta.duration*100+'%',width:(s.end-s.start)/doc.meta.duration*100+'%',background:s.color}}/>)}<i style={{left:a/doc.meta.duration*100+'%',width:span/doc.meta.duration*100+'%'}}/></div><button className="overview-reset" onClick={()=>setRange([0,doc.meta.duration])}>全曲</button></div>}
 <div className="timeline-fixed" ref={body}><div className="track-label ruler-label"><select aria-label="显示轨道" value={trackZone} onChange={e=>setTrackZone(e.target.value)}><option value="all">全部 24 点</option><option value="dam">坝顶 17 点</option><option value="front">小平台 7 点</option></select></div><div ref={ruler} className="ruler" {...bindSeek} role="slider" aria-label="演出播放头" aria-valuemin={a} aria-valuemax={b} aria-valuenow={Math.max(a,Math.min(b,time))} aria-valuetext={`${stamp(time,true)} 演出时间${time<a||time>b?'，播放头在当前视图之外':''}`} tabIndex={0}>{ticks.map(t=><span key={t} style={{left:pct(t)+'%'}}>{stamp(t)}</span>)}</div>
 <div className="track-label section-label"><select aria-label="选择编排段落" value={selectedSection?.id||''} onChange={e=>{const s=doc.sections.find(s=>s.id===e.target.value);if(s)onSection(s)}}><option value="" disabled>编排段落</option>{doc.sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="sections" {...bindSection} aria-label="拖选范围建立编排段落">{!doc.sections.length&&<span className="empty-sections">拖选时间范围建立段落，或点上方“建立段落”</span>}{sectionSelection&&<i className="section-range-selection" style={{left:pct(sectionSelection[0])+'%',width:(sectionSelection[1]-sectionSelection[0])/span*100+'%'}}/>}{doc.sections.filter(s=>s.end>a&&s.start<b).map(s=><button key={s.id} aria-label={`编排段落 ${s.name}`} aria-pressed={selectedSection?.id===s.id} title={`${s.name} · ${stamp(s.start)}–${stamp(s.end)}`} onClick={()=>onSection(s)} style={{left:pct(Math.max(a,s.start))+'%',width:(Math.min(b,s.end)-Math.max(a,s.start))/span*100+'%',background:s.color}}><span>{s.name}</span></button>)}</div>
 <div className="track-label music-label"><MusicNotes size={16}/><div><b>音乐</b><small>{!music.duration?'尚未导入':energy?'波形 + 能量':'原始波形'}</small></div></div><div className="music-lane" {...bindSeek} role="slider" aria-label="音乐波形定位" aria-valuemin={a} aria-valuemax={b} aria-valuenow={Math.max(a,Math.min(b,time))} aria-valuetext={`${stamp(time,true)} 演出时间${time<a||time>b?'，播放头在当前视图之外':''}`} tabIndex={0}><canvas ref={wave}/>{markers&&musicMarkers.filter(m=>m.time>=a&&m.time<=b&&['peak','climax'].includes(m.kind)).map(m=><button key={m.id} className="music-marker" style={{left:pct(m.time)+'%'}} title={`${m.name} · 自动分析待确认`} aria-label={`定位重音 ${stamp(m.time)}`} onPointerDown={e=>e.stopPropagation()} onClick={()=>onSeek(m.time)}><span/></button>)}{music.duration>0&&a<offset&&<span className="countdown-label" style={{width:Math.max(0,pct(offset))+'%'}}>倒计时</span>}</div>
 {time>=a&&time<=b&&<div className="fixed-head" style={{left:`calc(var(--track-label-width,144px) + (100% - var(--track-label-width,144px)) * ${pct(time)/100})`}}><button className="playhead-handle" aria-label="拖动播放头" title="拖动播放头" {...bindSeek}>{stamp(time)}</button></div>}</div>
 <div className="tracks-scroll" ref={tracks}>{groups.map(([g,label,count])=><React.Fragment key={g}><div className="group-row"><button className="track-label" onClick={()=>setOpen(o=>({...o,[g]:!o[g]}))} aria-expanded={open[g]}>{open[g]?<CaretDown size={13}/>:<CaretRight size={13}/>}<b>{label}</b><small>{count}</small></button><div className="track-plot group-plot">{!open[g]&&bars(eventGroups[g],true)}<Grid ticks={ticks} pct={pct}/>{time>=a&&time<=b&&<i className="track-head" {...bindSeek} style={{left:pct(time)+'%'}}/>}{open[g]&&<span className="group-summary">{count} 条点位轨道 · {eventGroups[g].length} 次播放</span>}</div></div>{open[g]&&doc.points.filter(p=>p.id.startsWith(g)&&(!solo||!point||point===p.id)).map(p=><div className={"track-row "+(point===p.id?"point-selected":"")} key={p.id} data-point={p.id}><button className="track-label point-label" aria-label={`选择点位 ${p.id}`} aria-pressed={point===p.id} onClick={e=>onPoint(p.id,e)} onDoubleClick={()=>onPointDouble(p.id)}><span className={'point-dot '+g}/><b>{p.id}</b><small>{g==='F'?'前台':g==='P'?'主花':'扇形'}</small></button><div className="track-plot"><Grid ticks={ticks} pct={pct}/>{bars(eventGroups[g].filter(e=>e.pointId===p.id))}{time>=a&&time<=b&&<i className="track-head" {...bindSeek} style={{left:pct(time)+'%'}}/>}</div></div>)}</React.Fragment>)}</div><div className="clip-feedback" aria-live="polite">{hover||`已选：${selected?.name||'无'} · 选择不改变播放范围`}</div>
 </div>
}
function Grid({ticks,pct}){return <div className="grid-lines">{ticks.map(t=><i key={t} style={{left:pct(t)+'%'}}/>)}</div>}
const short=n=>n.replace('坝顶·','').replace('前台·','');
