"""Generate scoped CSS tokens and an offline subset of the existing Tabler icons."""
import argparse
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent


def outputs():
    tokens = json.loads((HERE / 'tokens.json').read_text(encoding='utf-8'))
    lines = ['/* Generated by tool/design-system/build.py; edit tokens.json. */', '.fw-scope {']
    for group in ('color', 'type', 'space', 'radius', 'size', 'motion'):
        for name, value in tokens[group].items():
            if not re.fullmatch(r'[a-z0-9-]+', name):
                raise ValueError(f'Invalid token name: {name}')
            if group == 'color':
                if not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value):
                    raise ValueError(f'Invalid color: {name}')
                rendered = value
            else:
                if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
                    raise ValueError(f'Invalid metric: {name}')
                rendered = f'{value}{"ms" if group == "motion" else "px"}'
            lines.append(f'  --fw-{group}-{name}: {rendered};')
    lines.extend(['  --fw-control-height: var(--fw-size-control-compact);', '}', ''])

    source = (HERE.parent / 'src/js/69_icons.js').read_text(encoding='utf-8')
    license_text = re.search(r'/\*[\s\S]*?\*/', source).group(0)
    icons = json.loads(re.search(r'const UI_ICONS = (\{[^\n]+\});', source).group(1))
    aliases = {'undo': 'arrow-back-up', 'redo': 'arrow-forward-up', 'preview': 'eye',
               'hidden': 'eye-off', 'expand': 'chevron-down', 'play': 'player-play',
               'pause': 'player-pause', 'refresh': 'refresh'}
    subset = {name: icons[key] for name, key in aliases.items()}
    icon_js = '// Generated offline subset of existing Tabler Icons v3.46.0.\n' + license_text + '\n'
    icon_js += '(function () {\n  "use strict";\n  const icons = ' + json.dumps(subset, ensure_ascii=False) + ';\n'
    icon_js += '''  window.FWIcons = Object.freeze({
    apply(root = document) {
      root.querySelectorAll('[data-fw-icon]').forEach(node => {
        const uri = icons[node.dataset.fwIcon];
        if (!uri) throw new Error('Unknown workspace icon: ' + node.dataset.fwIcon);
        node.style.setProperty('--fw-icon-image', 'url("' + uri + '")');
        node.setAttribute('aria-hidden', 'true');
      });
    }
  });
})();
'''
    return {'tokens.css': '\n'.join(lines), 'icons.js': icon_js}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated files differ')
    args = parser.parse_args()
    for name, content in outputs().items():
        path = HERE / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Stale generated file: {name}; run build.py')
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print('Design foundations: generated files match' if args.check else 'Design foundations: generated tokens.css and icons.js')


if __name__ == '__main__':
    main()
