import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {sourceMapping,SOURCE_BP,sourceAlias} from '../src/director-source-map.mjs';
import {compileDirector} from '../src/director-model.mjs';import {migrateNumbering} from '../src/point-numbering.mjs';import {qualityEvents} from '../src/editing-model.mjs';
const state=migrateNumbering(JSON.parse(fs.readFileSync(new URL('../public/data/score24-v05.json',import.meta.url))));
const names=['FanComet','FanSilver','FanComet','GoldCrackle','Comet','GreenPeony','GoldSpark','PrismWheels','GoldChry','GoldKamuro','SilverStrobeChry'];
const catalog=names.map((name,i)=>({key:'s'+i,sourcePath:SOURCE_BP,sourceIndex:i,exportName:sourceAlias(i,name),sub:{TemplateName:name,Entries:[{FXResourceId:'P_'+name,LocalTimeOffset:i/2,PositionOffset:{X:0,Y:0,Z:i*100},RotationOffset:{Pitch:0,Yaw:0,Roll:0},EffectScale:{X:1,Y:1,Z:1}}]}}));
const target={catalog,sourceLibrary:{path:SOURCE_BP},points:state.doc.points.map(p=>({pointId:p.id,bindings:[{GroupName:p.id[0],SlotIndex:+p.id.slice(1)}]}))};
test('explicit source distinguishes duplicate names and rejects old catalogue',()=>{const m=sourceMapping(state.doc,catalog,'silver');assert.equal(m.G_RED5.source,'s2');assert.equal(m.G_GOLD.source,'s1');assert.equal(m.P_MULTI.source,'s7');assert(m.G_GOLD.note.includes('用户确认'));assert.throws(()=>sourceMapping(state.doc,catalog.map(c=>({...c,sourcePath:'/old'})),'silver'));assert.notEqual(sourceAlias(0,'FanComet'),sourceAlias(2,'FanComet'));});
test('source rows copy once and all three grades preserve source entries and exact event timing',()=>{for(const tier of ['high','medium','low']){const events=qualityEvents(state.doc,state.profiles,tier),m=sourceMapping(state.doc,catalog,'silver'),r=compileDirector(state.doc,events,target,m);assert.deepEqual(r.issues,[]);assert.equal(r.arrays.EffectSubTemplates.length,catalog.length);for(const c of catalog){const renamed=r.manifest.templateNaming.subTemplates.find(x=>x.from===c.exportName).to;assert.deepEqual(r.arrays.EffectSubTemplates.find(s=>s.TemplateName===renamed).Entries,c.sub.Entries);}let fan=0;for(const g of r.arrays.EffectScheduleGroups)for(const slot of g.Slots){const parent=r.arrays.EffectTemplates.find(t=>t.TemplateName===slot.TemplateName);for(const e of parent.Entries){const child=r.arrays.EffectSubTemplates.find(s=>s.TemplateName===e.SubTemplateName);if(child.Entries.some(e=>e.FXResourceId.includes('Fan')))fan++;assert(events.some(x=>x.pointId===g.GroupName+e.SlotIndex&&Math.abs(x.effectiveLaunch-slot.StartTime-e.LocalTimeOffset)<1e-5));}}assert.equal(fan,events.filter(e=>state.doc.templateLibrary.find(t=>t.id===e.templateId).kind==='fan').length);}});
test('fan source cannot silently replace ball flower',()=>{const m=sourceMapping(state.doc,catalog,'silver');m.P_LIME={...m.P_LIME,source:'s2'};assert(compileDirector(state.doc,qualityEvents(state.doc,state.profiles,'high'),target,m).issues.some(x=>x.includes('扇形素材')));});

test('sparse slots retain group capacity so high zero-based indices remain in range',()=>{const r=compileDirector(state.doc,qualityEvents(state.doc,state.profiles,'high'),target,sourceMapping(state.doc,target.catalog));for(const p of r.arrays.EffectTemplates)assert(p.Entries.every(e=>e.SlotIndex>=0&&e.SlotIndex<p.RequiredPointCount))});
