import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {migrateSubTemplates,previewSubTemplates,saveSubTemplate,compileSubTemplate} from '../src/subtemplate-model.mjs';
import {compileDirector} from '../src/director-model.mjs';import {migrateNumbering} from '../src/point-numbering.mjs';import {qualityEvents,validateDoc} from '../src/editing-model.mjs';import {makeBackup,parseBackup,editProgram} from '../src/workbench-data.mjs';
const seed=migrateNumbering(JSON.parse(fs.readFileSync(new URL('../public/data/score24-v05.json',import.meta.url))));
const source=JSON.parse(fs.readFileSync(new URL('../public/data/subtemplate-source.json',import.meta.url)));
const doc=migrateSubTemplates(seed.doc,source.catalog),state={...seed,doc};
const key=(point,time,n)=>JSON.stringify([point,Math.round(time*1e5)/1e5,n]);
test('migration keeps launch times, source native random, and valid timeline',()=>{assert.deepEqual(validateDoc(doc),[]);for(let i=0;i<doc.events.length;i++)assert(Math.abs(doc.events[i].effectiveLaunch-seed.doc.events[i].effectiveLaunch)<1e-6);assert.deepEqual(migrateSubTemplates(doc,source.catalog),doc);assert(compileSubTemplate(doc.subTemplateLibrary.find(s=>s.id==='ST_P_SILVER'))[0].RandomRotationRange);});
test('every native preview entry equals expansion of the three tables for all tiers',()=>{for(const tier of ['high','medium','low']){const events=qualityEvents(doc,state.profiles,tier),preview=previewSubTemplates(doc,events),result=compileDirector(doc,events);assert.deepEqual(result.issues,[]);const {EffectSubTemplates:subs,EffectTemplates:parents,EffectScheduleGroups:groups}=result.arrays;
 const actual=[];for(const g of groups)for(const slot of g.Slots){const p=parents.find(p=>p.TemplateName===slot.TemplateName);assert.equal(p.RequiredPointCount,{P:9,B:8,F:7}[g.GroupName]);for(const e of p.Entries)for(const n of subs.find(s=>s.TemplateName===e.SubTemplateName).Entries)actual.push(key(g.GroupName+e.SlotIndex,slot.StartTime+e.LocalTimeOffset+n.LocalTimeOffset,n));}
 assert.deepEqual(actual.sort(),preview.events.map(e=>key(e.pointId,e.effectiveLaunch,e.nativeEntry)).sort());}});
test('saved edits reach director output; backup restore and undo values retain exact versions',()=>{const t=doc.templateLibrary.find(t=>t.id==='G_GOLD'),old=doc.subTemplateLibrary.find(s=>s.key===t.subTemplateRef),draft=structuredClone(old);draft.entries[0].native.RotationOffset.Roll=27;draft.entries[0].native.LocalTimeOffset=.123;const next=saveSubTemplate(doc,t.id,draft);const result=compileDirector(next,qualityEvents(next,state.profiles,'high'));assert.deepEqual(result.issues,[]);assert(result.arrays.EffectSubTemplates.some(s=>s.Entries.some(e=>e.RotationOffset.Roll===27&&e.LocalTimeOffset===.123)));assert.deepEqual(parseBackup(JSON.stringify(makeBackup({...state,doc:next},seed)),seed).doc,next);assert.deepEqual(doc.subTemplateLibrary.find(s=>s.key===old.key),old);});
test('new and copied clips derive their duration from the fixed recipe',()=>{const added=editProgram(state,'add',{templateId:'G_GOLD',start:100});assert.deepEqual(validateDoc(added.doc),[]);const cue=added.doc.cues.find(c=>c.id===added.selectedCue),s=doc.subTemplateLibrary.find(s=>s.key==='ST_G_GOLD@1');const end=Math.max(...s.entries.map(e=>e.native.LocalTimeOffset+e.preview.durationS));for(const e of added.doc.events.filter(e=>e.cueId===cue.id))assert(Math.abs(e.end-e.launch-end)<1e-6);});
